// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\final_heart_sym3_3_Level_fixed\LoD_Odd.v
// Created: 2024-04-18 17:46:00
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LoD_Odd
// Source Path: final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Decomp/LoD_Odd
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LoD_Odd
          (clk,
           reset,
           enb,
           In_LoD_o,
           Out_LoD_o);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] In_LoD_o;  // ufix16_En24
  output  signed [15:0] Out_LoD_o;  // sfix16_En23


  wire signed [15:0] LoD_1_out1;  // sfix16_En18
  reg signed [15:0] LoD_1_out1_1;  // sfix16_En18
  reg [15:0] In_LoD_o_1;  // ufix16_En24
  wire signed [16:0] Multiply5_cast;  // sfix17_En24
  wire signed [32:0] Multiply5_mul_temp;  // sfix33_En42
  wire signed [31:0] Multiply5_cast_1;  // sfix32_En42
  wire signed [15:0] Multiply5_out1;  // sfix16_En15
  reg signed [15:0] Multiply5_out1_1;  // sfix16_En15
  wire [15:0] LoD_3_out1;  // ufix16_En17
  reg [15:0] LoD_3_out1_1;  // ufix16_En17
  reg [15:0] Rate_Transition_out1;  // ufix16_En24
  wire [31:0] Multiply3_mul_temp;  // ufix32_En41
  wire [15:0] Multiply3_out1;  // ufix16_En25
  reg [15:0] Multiply3_out1_1;  // ufix16_En25
  wire [15:0] LoD_5_out1;  // ufix16_En17
  reg [15:0] LoD_5_out1_1;  // ufix16_En17
  reg [15:0] Rate_Transition1_out1;  // ufix16_En24
  wire [31:0] Multiply4_mul_temp;  // ufix32_En41
  wire [15:0] Multiply4_out1;  // ufix16_En25
  reg [15:0] delayMatch_reg [0:1];  // ufix16 [2]
  wire [15:0] delayMatch_reg_next [0:1];  // ufix16_En25 [2]
  wire [15:0] Multiply4_out1_1;  // ufix16_En25
  wire [15:0] Add3_add_cast;  // ufix16_En24
  wire [15:0] Add3_add_cast_1;  // ufix16_En24
  wire [15:0] Add3_out1;  // ufix16_En24
  reg [15:0] Delay7_out1;  // ufix16_En24
  wire signed [15:0] Add2_add_cast;  // sfix16_En23
  wire signed [15:0] Add2_add_cast_1;  // sfix16_En23
  wire signed [15:0] Add2_out1;  // sfix16_En23


  assign LoD_1_out1 = 16'sb1010100010000010;


  always @(posedge clk)
    begin : HwModeRegister4_process
      if (reset == 1'b1) begin
        LoD_1_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_1_out1_1 <= LoD_1_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_process
      if (reset == 1'b1) begin
        In_LoD_o_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          In_LoD_o_1 <= In_LoD_o;
        end
      end
    end


  assign Multiply5_cast = {1'b0, In_LoD_o_1};
  assign Multiply5_mul_temp = LoD_1_out1_1 * Multiply5_cast;
  assign Multiply5_cast_1 = Multiply5_mul_temp[31:0];
  assign Multiply5_out1 = {{11{Multiply5_cast_1[31]}}, Multiply5_cast_1[31:27]};


  always @(posedge clk)
    begin : PipelineRegister2_process
      if (reset == 1'b1) begin
        Multiply5_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply5_out1_1 <= Multiply5_out1;
        end
      end
    end



  assign LoD_3_out1 = 16'b1110101101110101;


  always @(posedge clk)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        LoD_3_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_3_out1_1 <= LoD_3_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        Rate_Transition_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition_out1 <= In_LoD_o_1;
        end
      end
    end


  assign Multiply3_mul_temp = LoD_3_out1_1 * Rate_Transition_out1;
  assign Multiply3_out1 = Multiply3_mul_temp[31:16];


  always @(posedge clk)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Multiply3_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply3_out1_1 <= Multiply3_out1;
        end
      end
    end



  assign LoD_5_out1 = 16'b1010101001010100;


  always @(posedge clk)
    begin : HwModeRegister2_process
      if (reset == 1'b1) begin
        LoD_5_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_5_out1_1 <= LoD_5_out1;
        end
      end
    end



  always @(posedge clk)
    begin : HwModeRegister3_process
      if (reset == 1'b1) begin
        Rate_Transition1_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition1_out1 <= Rate_Transition_out1;
        end
      end
    end



  assign Multiply4_mul_temp = LoD_5_out1_1 * Rate_Transition1_out1;
  assign Multiply4_out1 = Multiply4_mul_temp[31:16];


  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 16'b0000000000000000;
        delayMatch_reg[1] <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
        end
      end
    end

  assign Multiply4_out1_1 = delayMatch_reg[1];
  assign delayMatch_reg_next[0] = Multiply4_out1;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];



  assign Add3_add_cast = {1'b0, Multiply3_out1_1[15:1]};
  assign Add3_add_cast_1 = {1'b0, Multiply4_out1_1[15:1]};
  assign Add3_out1 = Add3_add_cast + Add3_add_cast_1;


  always @(posedge clk)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= Add3_out1;
        end
      end
    end


  assign Add2_add_cast = {Multiply5_out1_1[7:0], 8'b00000000};
  assign Add2_add_cast_1 = {1'b0, Delay7_out1[15:1]};
  assign Add2_out1 = Add2_add_cast + Add2_add_cast_1;


  assign Out_LoD_o = Add2_out1;

endmodule  // LoD_Odd

