// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\final_heart_sym2_level4_hdl\Data_Sorter22.v
// Created: 2024-04-18 15:10:40
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Data_Sorter22
// Source Path: final_heart_sym2_level4_hdl/DWT_Sym2_Level4/Threshold_Estimator/Median2/Data_Sorter22
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Data_Sorter22
          (clk,
           reset,
           enb,
           Signal1,
           Signal2,
           Low_Data);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] Signal1;  // ufix16_En27
  input   [15:0] Signal2;  // ufix16_En27
  output  [15:0] Low_Data;  // ufix16_En27


  wire Relational_Operator2_relop1;
  wire switch_compare_1;
  wire [15:0] Data_Sorter_Switch1_out1;  // ufix16_En27
  reg [15:0] Delay2_out1;  // ufix16_En27


  assign Relational_Operator2_relop1 = Signal1 < Signal2;


  assign switch_compare_1 = Relational_Operator2_relop1 == 1'b1;



  assign Data_Sorter_Switch1_out1 = (switch_compare_1 == 1'b0 ? Signal2 :
              Signal2);


  always @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Data_Sorter_Switch1_out1;
        end
      end
    end


  assign Low_Data = Delay2_out1;

endmodule  // Data_Sorter22

