// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\final_heart_sym3_3_Level_fixed\LoD_Even_block.v
// Created: 2024-04-18 15:47:41
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LoD_Even_block
// Source Path: final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Decomp1/LoD_Even
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LoD_Even_block
          (clk,
           reset,
           enb,
           In_LoD_e,
           Out_LoD_e);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In_LoD_e;  // sfix16_En23
  output  signed [15:0] Out_LoD_e;  // sfix16_En24


  wire [15:0] LoD_1_out1;  // ufix16_En20
  reg [15:0] LoD_1_out1_1;  // ufix16_En20
  reg signed [15:0] In_LoD_e_1;  // sfix16_En23
  wire signed [16:0] Multiply5_cast;  // sfix17_En20
  wire signed [32:0] Multiply5_mul_temp;  // sfix33_En43
  wire signed [31:0] Multiply5_cast_1;  // sfix32_En43
  wire [15:0] Multiply5_out1;  // ufix16_En29
  reg [15:0] Multiply5_out1_1;  // ufix16_En29
  wire signed [15:0] LoD_3_out1;  // sfix16_En17
  reg signed [15:0] LoD_3_out1_1;  // sfix16_En17
  reg signed [15:0] Rate_Transition_out1;  // sfix16_En23
  wire signed [31:0] Multiply3_mul_temp;  // sfix32_En40
  wire signed [15:0] Multiply3_out1;  // sfix16_En15
  reg signed [15:0] Multiply3_out1_1;  // sfix16_En15
  wire [15:0] LoD_5_out1;  // ufix16_En16
  reg [15:0] LoD_5_out1_1;  // ufix16_En16
  reg signed [15:0] Rate_Transition1_out1;  // sfix16_En23
  wire signed [16:0] Multiply4_cast;  // sfix17_En16
  wire signed [32:0] Multiply4_mul_temp;  // sfix33_En39
  wire signed [31:0] Multiply4_cast_1;  // sfix32_En39
  wire [15:0] Multiply4_out1;  // ufix16_En24
  reg [15:0] delayMatch_reg [0:1];  // ufix16 [2]
  wire [15:0] delayMatch_reg_next [0:1];  // ufix16_En24 [2]
  wire [15:0] Multiply4_out1_1;  // ufix16_En24
  wire signed [15:0] Add3_add_cast;  // sfix16_En23
  wire signed [15:0] Add3_add_cast_1;  // sfix16_En23
  wire signed [15:0] Add3_add_temp;  // sfix16_En23
  wire signed [15:0] Add3_out1;  // sfix16_En24
  reg signed [15:0] Delay7_out1;  // sfix16_En24
  wire signed [15:0] Add2_add_cast;  // sfix16_En24
  wire signed [15:0] Add2_out1;  // sfix16_En24


@[tracestart]
  // '<S18>/LoD_1'
  assign LoD_1_out1 = 16'b1001000001001001;


@[traceend]
  always @(posedge clk)
    begin : HwModeRegister4_process
      if (reset == 1'b1) begin
        LoD_1_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_1_out1_1 <= LoD_1_out1;
        end
      end
    end



@[tracestart]
  // '<S18>/Delay4'
  // 
  // '<S18>/Rate Transition'
  always @(posedge clk)
    begin : reduced_process
      if (reset == 1'b1) begin
        In_LoD_e_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          In_LoD_e_1 <= In_LoD_e;
        end
      end
    end


@[traceend]
@[tracestart]
  // '<S18>/Multiply5'
  assign Multiply5_cast = {1'b0, LoD_1_out1_1};
  assign Multiply5_mul_temp = Multiply5_cast * In_LoD_e_1;
  assign Multiply5_cast_1 = Multiply5_mul_temp[31:0];
  assign Multiply5_out1 = Multiply5_cast_1[29:14];


@[traceend]
  always @(posedge clk)
    begin : PipelineRegister2_process
      if (reset == 1'b1) begin
        Multiply5_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply5_out1_1 <= Multiply5_out1;
        end
      end
    end



@[tracestart]
  // '<S18>/LoD_3'
  assign LoD_3_out1 = 16'sb1011101011100000;


@[traceend]
  always @(posedge clk)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        LoD_3_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_3_out1_1 <= LoD_3_out1;
        end
      end
    end



@[tracestart]
  // '<S18>/Delay5'
  // 
  // '<S18>/Rate Transition1'
  always @(posedge clk)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        Rate_Transition_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition_out1 <= In_LoD_e_1;
        end
      end
    end


@[traceend]
@[tracestart]
  // '<S18>/Multiply3'
  assign Multiply3_mul_temp = LoD_3_out1_1 * Rate_Transition_out1;
  assign Multiply3_out1 = {{9{Multiply3_mul_temp[31]}}, Multiply3_mul_temp[31:25]};


@[traceend]
  always @(posedge clk)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Multiply3_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply3_out1_1 <= Multiply3_out1;
        end
      end
    end



@[tracestart]
  // '<S18>/LoD_5'
  assign LoD_5_out1 = 16'b1100111010010000;


@[traceend]
  always @(posedge clk)
    begin : HwModeRegister2_process
      if (reset == 1'b1) begin
        LoD_5_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_5_out1_1 <= LoD_5_out1;
        end
      end
    end



  always @(posedge clk)
    begin : HwModeRegister3_process
      if (reset == 1'b1) begin
        Rate_Transition1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition1_out1 <= Rate_Transition_out1;
        end
      end
    end



@[tracestart]
  // '<S18>/Multiply4'
  // 
  // '<S18>/Delay6'
  assign Multiply4_cast = {1'b0, LoD_5_out1_1};
  assign Multiply4_mul_temp = Multiply4_cast * Rate_Transition1_out1;
  assign Multiply4_cast_1 = Multiply4_mul_temp[31:0];
  assign Multiply4_out1 = Multiply4_cast_1[30:15];


@[traceend]
  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 16'b0000000000000000;
        delayMatch_reg[1] <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
        end
      end
    end

  assign Multiply4_out1_1 = delayMatch_reg[1];
  assign delayMatch_reg_next[0] = Multiply4_out1;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];



@[tracestart]
  // '<S18>/Add3'
  assign Add3_add_cast = {Multiply3_out1_1[7:0], 8'b00000000};
  assign Add3_add_cast_1 = {1'b0, Multiply4_out1_1[15:1]};
  assign Add3_add_temp = Add3_add_cast + Add3_add_cast_1;
  assign Add3_out1 = {Add3_add_temp[14:0], 1'b0};


@[traceend]
@[tracestart]
  // '<S18>/Delay7'
  always @(posedge clk)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= Add3_out1;
        end
      end
    end


@[traceend]
@[tracestart]
  // '<S18>/Add2'
  assign Add2_add_cast = {5'b0, Multiply5_out1_1[15:5]};
  assign Add2_out1 = Add2_add_cast + Delay7_out1;


@[traceend]
  assign Out_LoD_e = Add2_out1;

endmodule  // LoD_Even_block

