open_system('gm_final_heart_sym3_3_Level_fixed');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon', 'user2');
annotate_port('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon', 0, 1, 'cp : 14.634 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/HiR_Even', 'user2');
annotate_port('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/HiR_Even', 0, 1, 'cp : 4.759 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/Add3', 'user2');
annotate_port('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/Add3', 0, 1, 'cp : 9.518 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/Add5', 'user2');
annotate_port('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/Add5', 0, 1, 'cp : 14.277 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/HwModeRegister1', 'user1');
annotate_port('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/HwModeRegister1', 1, 1, 'cp : 14.634 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/HiR_Even/Add', 'user2');
annotate_port('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/HiR_Even/Add', 0, 1, 'cp : 4.759 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/HiR_Even/PipelineRegister', 'user1');
annotate_port('gm_final_heart_sym3_3_Level_fixed/DWT_sym3_3_Level/1st_Level_Recon/HiR_Even/PipelineRegister', 0, 1, 'cp : 0 ns');
