vlib work
vcom  DWT_db3_2_Level_pkg.vhd
vcom  HiD_Even.vhd
vcom  HiD_Odd.vhd
vcom  LoD_Even.vhd
vcom  LoD_Odd.vhd
vcom  alpha1st_Level_Decomp.vhd
vcom  HiR_Even.vhd
vcom  HiR_Odd.vhd
vcom  LoR_Even.vhd
vcom  LoR_Odd.vhd
vcom  alpha1st_Level_Recon.vhd
vcom  HiD_Even_block.vhd
vcom  HiD_Odd_block.vhd
vcom  LoD_Even_block.vhd
vcom  LoD_Odd_block.vhd
vcom  alpha2nd_Level_Decomp.vhd
vcom  HiR_Even_block.vhd
vcom  HiR_Odd_block.vhd
vcom  LoR_Even_block.vhd
vcom  LoR_Odd_block.vhd
vcom  alpha2nd_Level_Recon.vhd
vcom  Soft_Thresholding.vhd
vcom  Soft_Thresholding1.vhd
vcom  Absolute_Value1.vhd
vcom  Data_Sorter1.vhd
vcom  Data_Sorter10.vhd
vcom  Data_Sorter11.vhd
vcom  Data_Sorter12.vhd
vcom  Data_Sorter13.vhd
vcom  Data_Sorter14.vhd
vcom  Data_Sorter15.vhd
vcom  Data_Sorter16.vhd
vcom  Data_Sorter17.vhd
vcom  Data_Sorter18.vhd
vcom  Data_Sorter19.vhd
vcom  Data_Sorter2.vhd
vcom  Data_Sorter20.vhd
vcom  Data_Sorter21.vhd
vcom  Data_Sorter22.vhd
vcom  Data_Sorter23.vhd
vcom  Data_Sorter24.vhd
vcom  Data_Sorter3.vhd
vcom  Data_Sorter4.vhd
vcom  Data_Sorter5.vhd
vcom  Data_Sorter6.vhd
vcom  Data_Sorter7.vhd
vcom  Data_Sorter8.vhd
vcom  Data_Sorter9.vhd
vcom  Median2.vhd
vcom  Threshold_Estimator.vhd
vcom  DWT_db3_2_Level_tc.vhd
vcom  DWT_db3_2_Level.vhd
