// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\final_heart_sym2_level4_hdl\alpha1st_Level_Recon2.v
// Created: 2024-04-17 11:34:26
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: alpha1st_Level_Recon2
// Source Path: final_heart_sym2_level4_hdl/DWT_Sym2_Level4/1st_Level_Recon2
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alpha1st_Level_Recon2
          (clk,
           reset,
           enb,
           In_HiD,
           In_LoD,
           Out);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In_HiD;  // sfix16_En27
  input   signed [15:0] In_LoD;  // sfix16_En23
  output  signed [15:0] Out;  // sfix16_En22


  wire [15:0] kconst;  // ufix16_En16
  reg [15:0] kconst_1;  // ufix16_En16
  wire signed [15:0] HiR_Even_out1;  // sfix16_En28
  reg signed [15:0] delayMatch_reg [0:119];  // sfix16 [120]
  wire signed [15:0] delayMatch_reg_next [0:119];  // sfix16_En28 [120]
  wire signed [15:0] HiR_Even_out1_1;  // sfix16_En28
  wire signed [15:0] LoR_Even_out1;  // sfix16_En23
  wire signed [15:0] Add_add_cast;  // sfix16_En23
  wire signed [15:0] Add_out1;  // sfix16_En23
  wire signed [15:0] HiR_Odd_out1;  // sfix16_En29
  reg signed [15:0] delayMatch1_reg [0:119];  // sfix16 [120]
  wire signed [15:0] delayMatch1_reg_next [0:119];  // sfix16_En29 [120]
  wire signed [15:0] HiR_Odd_out1_1;  // sfix16_En29
  wire signed [15:0] LoR_Odd_out1;  // sfix16_En23
  wire signed [15:0] Add1_add_cast;  // sfix16_En23
  wire signed [15:0] Add1_out1;  // sfix16_En23
  reg signed [15:0] Delay2_out1;  // sfix16_En23
  wire signed [15:0] Add2_add_cast;  // sfix16_En22
  wire signed [15:0] Add2_add_cast_1;  // sfix16_En22
  wire signed [15:0] Add2_out1;  // sfix16_En22
  reg signed [15:0] Add2_out1_1;  // sfix16_En22
  wire signed [16:0] Gain_cast;  // sfix17_En16
  wire signed [32:0] Gain_mul_temp;  // sfix33_En38
  wire signed [31:0] Gain_cast_1;  // sfix32_En38
  wire signed [15:0] Gain_out1;  // sfix16_En22
  reg signed [15:0] Gain_out1_1;  // sfix16_En22


  assign kconst = 16'b1101011000100110;



  always @(posedge clk)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        kconst_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          kconst_1 <= kconst;
        end
      end
    end



  HiR_Even_block1 u_HiR_Even (.clk(clk),
                              .reset(reset),
                              .enb(enb),
                              .In_HiR_e(In_HiD),  // sfix16_En27
                              .Out_HiR_e(HiR_Even_out1)  // sfix16_En28
                              );
  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 16'sb0000000000000000;
        delayMatch_reg[1] <= 16'sb0000000000000000;
        delayMatch_reg[2] <= 16'sb0000000000000000;
        delayMatch_reg[3] <= 16'sb0000000000000000;
        delayMatch_reg[4] <= 16'sb0000000000000000;
        delayMatch_reg[5] <= 16'sb0000000000000000;
        delayMatch_reg[6] <= 16'sb0000000000000000;
        delayMatch_reg[7] <= 16'sb0000000000000000;
        delayMatch_reg[8] <= 16'sb0000000000000000;
        delayMatch_reg[9] <= 16'sb0000000000000000;
        delayMatch_reg[10] <= 16'sb0000000000000000;
        delayMatch_reg[11] <= 16'sb0000000000000000;
        delayMatch_reg[12] <= 16'sb0000000000000000;
        delayMatch_reg[13] <= 16'sb0000000000000000;
        delayMatch_reg[14] <= 16'sb0000000000000000;
        delayMatch_reg[15] <= 16'sb0000000000000000;
        delayMatch_reg[16] <= 16'sb0000000000000000;
        delayMatch_reg[17] <= 16'sb0000000000000000;
        delayMatch_reg[18] <= 16'sb0000000000000000;
        delayMatch_reg[19] <= 16'sb0000000000000000;
        delayMatch_reg[20] <= 16'sb0000000000000000;
        delayMatch_reg[21] <= 16'sb0000000000000000;
        delayMatch_reg[22] <= 16'sb0000000000000000;
        delayMatch_reg[23] <= 16'sb0000000000000000;
        delayMatch_reg[24] <= 16'sb0000000000000000;
        delayMatch_reg[25] <= 16'sb0000000000000000;
        delayMatch_reg[26] <= 16'sb0000000000000000;
        delayMatch_reg[27] <= 16'sb0000000000000000;
        delayMatch_reg[28] <= 16'sb0000000000000000;
        delayMatch_reg[29] <= 16'sb0000000000000000;
        delayMatch_reg[30] <= 16'sb0000000000000000;
        delayMatch_reg[31] <= 16'sb0000000000000000;
        delayMatch_reg[32] <= 16'sb0000000000000000;
        delayMatch_reg[33] <= 16'sb0000000000000000;
        delayMatch_reg[34] <= 16'sb0000000000000000;
        delayMatch_reg[35] <= 16'sb0000000000000000;
        delayMatch_reg[36] <= 16'sb0000000000000000;
        delayMatch_reg[37] <= 16'sb0000000000000000;
        delayMatch_reg[38] <= 16'sb0000000000000000;
        delayMatch_reg[39] <= 16'sb0000000000000000;
        delayMatch_reg[40] <= 16'sb0000000000000000;
        delayMatch_reg[41] <= 16'sb0000000000000000;
        delayMatch_reg[42] <= 16'sb0000000000000000;
        delayMatch_reg[43] <= 16'sb0000000000000000;
        delayMatch_reg[44] <= 16'sb0000000000000000;
        delayMatch_reg[45] <= 16'sb0000000000000000;
        delayMatch_reg[46] <= 16'sb0000000000000000;
        delayMatch_reg[47] <= 16'sb0000000000000000;
        delayMatch_reg[48] <= 16'sb0000000000000000;
        delayMatch_reg[49] <= 16'sb0000000000000000;
        delayMatch_reg[50] <= 16'sb0000000000000000;
        delayMatch_reg[51] <= 16'sb0000000000000000;
        delayMatch_reg[52] <= 16'sb0000000000000000;
        delayMatch_reg[53] <= 16'sb0000000000000000;
        delayMatch_reg[54] <= 16'sb0000000000000000;
        delayMatch_reg[55] <= 16'sb0000000000000000;
        delayMatch_reg[56] <= 16'sb0000000000000000;
        delayMatch_reg[57] <= 16'sb0000000000000000;
        delayMatch_reg[58] <= 16'sb0000000000000000;
        delayMatch_reg[59] <= 16'sb0000000000000000;
        delayMatch_reg[60] <= 16'sb0000000000000000;
        delayMatch_reg[61] <= 16'sb0000000000000000;
        delayMatch_reg[62] <= 16'sb0000000000000000;
        delayMatch_reg[63] <= 16'sb0000000000000000;
        delayMatch_reg[64] <= 16'sb0000000000000000;
        delayMatch_reg[65] <= 16'sb0000000000000000;
        delayMatch_reg[66] <= 16'sb0000000000000000;
        delayMatch_reg[67] <= 16'sb0000000000000000;
        delayMatch_reg[68] <= 16'sb0000000000000000;
        delayMatch_reg[69] <= 16'sb0000000000000000;
        delayMatch_reg[70] <= 16'sb0000000000000000;
        delayMatch_reg[71] <= 16'sb0000000000000000;
        delayMatch_reg[72] <= 16'sb0000000000000000;
        delayMatch_reg[73] <= 16'sb0000000000000000;
        delayMatch_reg[74] <= 16'sb0000000000000000;
        delayMatch_reg[75] <= 16'sb0000000000000000;
        delayMatch_reg[76] <= 16'sb0000000000000000;
        delayMatch_reg[77] <= 16'sb0000000000000000;
        delayMatch_reg[78] <= 16'sb0000000000000000;
        delayMatch_reg[79] <= 16'sb0000000000000000;
        delayMatch_reg[80] <= 16'sb0000000000000000;
        delayMatch_reg[81] <= 16'sb0000000000000000;
        delayMatch_reg[82] <= 16'sb0000000000000000;
        delayMatch_reg[83] <= 16'sb0000000000000000;
        delayMatch_reg[84] <= 16'sb0000000000000000;
        delayMatch_reg[85] <= 16'sb0000000000000000;
        delayMatch_reg[86] <= 16'sb0000000000000000;
        delayMatch_reg[87] <= 16'sb0000000000000000;
        delayMatch_reg[88] <= 16'sb0000000000000000;
        delayMatch_reg[89] <= 16'sb0000000000000000;
        delayMatch_reg[90] <= 16'sb0000000000000000;
        delayMatch_reg[91] <= 16'sb0000000000000000;
        delayMatch_reg[92] <= 16'sb0000000000000000;
        delayMatch_reg[93] <= 16'sb0000000000000000;
        delayMatch_reg[94] <= 16'sb0000000000000000;
        delayMatch_reg[95] <= 16'sb0000000000000000;
        delayMatch_reg[96] <= 16'sb0000000000000000;
        delayMatch_reg[97] <= 16'sb0000000000000000;
        delayMatch_reg[98] <= 16'sb0000000000000000;
        delayMatch_reg[99] <= 16'sb0000000000000000;
        delayMatch_reg[100] <= 16'sb0000000000000000;
        delayMatch_reg[101] <= 16'sb0000000000000000;
        delayMatch_reg[102] <= 16'sb0000000000000000;
        delayMatch_reg[103] <= 16'sb0000000000000000;
        delayMatch_reg[104] <= 16'sb0000000000000000;
        delayMatch_reg[105] <= 16'sb0000000000000000;
        delayMatch_reg[106] <= 16'sb0000000000000000;
        delayMatch_reg[107] <= 16'sb0000000000000000;
        delayMatch_reg[108] <= 16'sb0000000000000000;
        delayMatch_reg[109] <= 16'sb0000000000000000;
        delayMatch_reg[110] <= 16'sb0000000000000000;
        delayMatch_reg[111] <= 16'sb0000000000000000;
        delayMatch_reg[112] <= 16'sb0000000000000000;
        delayMatch_reg[113] <= 16'sb0000000000000000;
        delayMatch_reg[114] <= 16'sb0000000000000000;
        delayMatch_reg[115] <= 16'sb0000000000000000;
        delayMatch_reg[116] <= 16'sb0000000000000000;
        delayMatch_reg[117] <= 16'sb0000000000000000;
        delayMatch_reg[118] <= 16'sb0000000000000000;
        delayMatch_reg[119] <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
          delayMatch_reg[2] <= delayMatch_reg_next[2];
          delayMatch_reg[3] <= delayMatch_reg_next[3];
          delayMatch_reg[4] <= delayMatch_reg_next[4];
          delayMatch_reg[5] <= delayMatch_reg_next[5];
          delayMatch_reg[6] <= delayMatch_reg_next[6];
          delayMatch_reg[7] <= delayMatch_reg_next[7];
          delayMatch_reg[8] <= delayMatch_reg_next[8];
          delayMatch_reg[9] <= delayMatch_reg_next[9];
          delayMatch_reg[10] <= delayMatch_reg_next[10];
          delayMatch_reg[11] <= delayMatch_reg_next[11];
          delayMatch_reg[12] <= delayMatch_reg_next[12];
          delayMatch_reg[13] <= delayMatch_reg_next[13];
          delayMatch_reg[14] <= delayMatch_reg_next[14];
          delayMatch_reg[15] <= delayMatch_reg_next[15];
          delayMatch_reg[16] <= delayMatch_reg_next[16];
          delayMatch_reg[17] <= delayMatch_reg_next[17];
          delayMatch_reg[18] <= delayMatch_reg_next[18];
          delayMatch_reg[19] <= delayMatch_reg_next[19];
          delayMatch_reg[20] <= delayMatch_reg_next[20];
          delayMatch_reg[21] <= delayMatch_reg_next[21];
          delayMatch_reg[22] <= delayMatch_reg_next[22];
          delayMatch_reg[23] <= delayMatch_reg_next[23];
          delayMatch_reg[24] <= delayMatch_reg_next[24];
          delayMatch_reg[25] <= delayMatch_reg_next[25];
          delayMatch_reg[26] <= delayMatch_reg_next[26];
          delayMatch_reg[27] <= delayMatch_reg_next[27];
          delayMatch_reg[28] <= delayMatch_reg_next[28];
          delayMatch_reg[29] <= delayMatch_reg_next[29];
          delayMatch_reg[30] <= delayMatch_reg_next[30];
          delayMatch_reg[31] <= delayMatch_reg_next[31];
          delayMatch_reg[32] <= delayMatch_reg_next[32];
          delayMatch_reg[33] <= delayMatch_reg_next[33];
          delayMatch_reg[34] <= delayMatch_reg_next[34];
          delayMatch_reg[35] <= delayMatch_reg_next[35];
          delayMatch_reg[36] <= delayMatch_reg_next[36];
          delayMatch_reg[37] <= delayMatch_reg_next[37];
          delayMatch_reg[38] <= delayMatch_reg_next[38];
          delayMatch_reg[39] <= delayMatch_reg_next[39];
          delayMatch_reg[40] <= delayMatch_reg_next[40];
          delayMatch_reg[41] <= delayMatch_reg_next[41];
          delayMatch_reg[42] <= delayMatch_reg_next[42];
          delayMatch_reg[43] <= delayMatch_reg_next[43];
          delayMatch_reg[44] <= delayMatch_reg_next[44];
          delayMatch_reg[45] <= delayMatch_reg_next[45];
          delayMatch_reg[46] <= delayMatch_reg_next[46];
          delayMatch_reg[47] <= delayMatch_reg_next[47];
          delayMatch_reg[48] <= delayMatch_reg_next[48];
          delayMatch_reg[49] <= delayMatch_reg_next[49];
          delayMatch_reg[50] <= delayMatch_reg_next[50];
          delayMatch_reg[51] <= delayMatch_reg_next[51];
          delayMatch_reg[52] <= delayMatch_reg_next[52];
          delayMatch_reg[53] <= delayMatch_reg_next[53];
          delayMatch_reg[54] <= delayMatch_reg_next[54];
          delayMatch_reg[55] <= delayMatch_reg_next[55];
          delayMatch_reg[56] <= delayMatch_reg_next[56];
          delayMatch_reg[57] <= delayMatch_reg_next[57];
          delayMatch_reg[58] <= delayMatch_reg_next[58];
          delayMatch_reg[59] <= delayMatch_reg_next[59];
          delayMatch_reg[60] <= delayMatch_reg_next[60];
          delayMatch_reg[61] <= delayMatch_reg_next[61];
          delayMatch_reg[62] <= delayMatch_reg_next[62];
          delayMatch_reg[63] <= delayMatch_reg_next[63];
          delayMatch_reg[64] <= delayMatch_reg_next[64];
          delayMatch_reg[65] <= delayMatch_reg_next[65];
          delayMatch_reg[66] <= delayMatch_reg_next[66];
          delayMatch_reg[67] <= delayMatch_reg_next[67];
          delayMatch_reg[68] <= delayMatch_reg_next[68];
          delayMatch_reg[69] <= delayMatch_reg_next[69];
          delayMatch_reg[70] <= delayMatch_reg_next[70];
          delayMatch_reg[71] <= delayMatch_reg_next[71];
          delayMatch_reg[72] <= delayMatch_reg_next[72];
          delayMatch_reg[73] <= delayMatch_reg_next[73];
          delayMatch_reg[74] <= delayMatch_reg_next[74];
          delayMatch_reg[75] <= delayMatch_reg_next[75];
          delayMatch_reg[76] <= delayMatch_reg_next[76];
          delayMatch_reg[77] <= delayMatch_reg_next[77];
          delayMatch_reg[78] <= delayMatch_reg_next[78];
          delayMatch_reg[79] <= delayMatch_reg_next[79];
          delayMatch_reg[80] <= delayMatch_reg_next[80];
          delayMatch_reg[81] <= delayMatch_reg_next[81];
          delayMatch_reg[82] <= delayMatch_reg_next[82];
          delayMatch_reg[83] <= delayMatch_reg_next[83];
          delayMatch_reg[84] <= delayMatch_reg_next[84];
          delayMatch_reg[85] <= delayMatch_reg_next[85];
          delayMatch_reg[86] <= delayMatch_reg_next[86];
          delayMatch_reg[87] <= delayMatch_reg_next[87];
          delayMatch_reg[88] <= delayMatch_reg_next[88];
          delayMatch_reg[89] <= delayMatch_reg_next[89];
          delayMatch_reg[90] <= delayMatch_reg_next[90];
          delayMatch_reg[91] <= delayMatch_reg_next[91];
          delayMatch_reg[92] <= delayMatch_reg_next[92];
          delayMatch_reg[93] <= delayMatch_reg_next[93];
          delayMatch_reg[94] <= delayMatch_reg_next[94];
          delayMatch_reg[95] <= delayMatch_reg_next[95];
          delayMatch_reg[96] <= delayMatch_reg_next[96];
          delayMatch_reg[97] <= delayMatch_reg_next[97];
          delayMatch_reg[98] <= delayMatch_reg_next[98];
          delayMatch_reg[99] <= delayMatch_reg_next[99];
          delayMatch_reg[100] <= delayMatch_reg_next[100];
          delayMatch_reg[101] <= delayMatch_reg_next[101];
          delayMatch_reg[102] <= delayMatch_reg_next[102];
          delayMatch_reg[103] <= delayMatch_reg_next[103];
          delayMatch_reg[104] <= delayMatch_reg_next[104];
          delayMatch_reg[105] <= delayMatch_reg_next[105];
          delayMatch_reg[106] <= delayMatch_reg_next[106];
          delayMatch_reg[107] <= delayMatch_reg_next[107];
          delayMatch_reg[108] <= delayMatch_reg_next[108];
          delayMatch_reg[109] <= delayMatch_reg_next[109];
          delayMatch_reg[110] <= delayMatch_reg_next[110];
          delayMatch_reg[111] <= delayMatch_reg_next[111];
          delayMatch_reg[112] <= delayMatch_reg_next[112];
          delayMatch_reg[113] <= delayMatch_reg_next[113];
          delayMatch_reg[114] <= delayMatch_reg_next[114];
          delayMatch_reg[115] <= delayMatch_reg_next[115];
          delayMatch_reg[116] <= delayMatch_reg_next[116];
          delayMatch_reg[117] <= delayMatch_reg_next[117];
          delayMatch_reg[118] <= delayMatch_reg_next[118];
          delayMatch_reg[119] <= delayMatch_reg_next[119];
        end
      end
    end

  assign HiR_Even_out1_1 = delayMatch_reg[119];
  assign delayMatch_reg_next[0] = HiR_Even_out1;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];
  assign delayMatch_reg_next[2] = delayMatch_reg[1];
  assign delayMatch_reg_next[3] = delayMatch_reg[2];
  assign delayMatch_reg_next[4] = delayMatch_reg[3];
  assign delayMatch_reg_next[5] = delayMatch_reg[4];
  assign delayMatch_reg_next[6] = delayMatch_reg[5];
  assign delayMatch_reg_next[7] = delayMatch_reg[6];
  assign delayMatch_reg_next[8] = delayMatch_reg[7];
  assign delayMatch_reg_next[9] = delayMatch_reg[8];
  assign delayMatch_reg_next[10] = delayMatch_reg[9];
  assign delayMatch_reg_next[11] = delayMatch_reg[10];
  assign delayMatch_reg_next[12] = delayMatch_reg[11];
  assign delayMatch_reg_next[13] = delayMatch_reg[12];
  assign delayMatch_reg_next[14] = delayMatch_reg[13];
  assign delayMatch_reg_next[15] = delayMatch_reg[14];
  assign delayMatch_reg_next[16] = delayMatch_reg[15];
  assign delayMatch_reg_next[17] = delayMatch_reg[16];
  assign delayMatch_reg_next[18] = delayMatch_reg[17];
  assign delayMatch_reg_next[19] = delayMatch_reg[18];
  assign delayMatch_reg_next[20] = delayMatch_reg[19];
  assign delayMatch_reg_next[21] = delayMatch_reg[20];
  assign delayMatch_reg_next[22] = delayMatch_reg[21];
  assign delayMatch_reg_next[23] = delayMatch_reg[22];
  assign delayMatch_reg_next[24] = delayMatch_reg[23];
  assign delayMatch_reg_next[25] = delayMatch_reg[24];
  assign delayMatch_reg_next[26] = delayMatch_reg[25];
  assign delayMatch_reg_next[27] = delayMatch_reg[26];
  assign delayMatch_reg_next[28] = delayMatch_reg[27];
  assign delayMatch_reg_next[29] = delayMatch_reg[28];
  assign delayMatch_reg_next[30] = delayMatch_reg[29];
  assign delayMatch_reg_next[31] = delayMatch_reg[30];
  assign delayMatch_reg_next[32] = delayMatch_reg[31];
  assign delayMatch_reg_next[33] = delayMatch_reg[32];
  assign delayMatch_reg_next[34] = delayMatch_reg[33];
  assign delayMatch_reg_next[35] = delayMatch_reg[34];
  assign delayMatch_reg_next[36] = delayMatch_reg[35];
  assign delayMatch_reg_next[37] = delayMatch_reg[36];
  assign delayMatch_reg_next[38] = delayMatch_reg[37];
  assign delayMatch_reg_next[39] = delayMatch_reg[38];
  assign delayMatch_reg_next[40] = delayMatch_reg[39];
  assign delayMatch_reg_next[41] = delayMatch_reg[40];
  assign delayMatch_reg_next[42] = delayMatch_reg[41];
  assign delayMatch_reg_next[43] = delayMatch_reg[42];
  assign delayMatch_reg_next[44] = delayMatch_reg[43];
  assign delayMatch_reg_next[45] = delayMatch_reg[44];
  assign delayMatch_reg_next[46] = delayMatch_reg[45];
  assign delayMatch_reg_next[47] = delayMatch_reg[46];
  assign delayMatch_reg_next[48] = delayMatch_reg[47];
  assign delayMatch_reg_next[49] = delayMatch_reg[48];
  assign delayMatch_reg_next[50] = delayMatch_reg[49];
  assign delayMatch_reg_next[51] = delayMatch_reg[50];
  assign delayMatch_reg_next[52] = delayMatch_reg[51];
  assign delayMatch_reg_next[53] = delayMatch_reg[52];
  assign delayMatch_reg_next[54] = delayMatch_reg[53];
  assign delayMatch_reg_next[55] = delayMatch_reg[54];
  assign delayMatch_reg_next[56] = delayMatch_reg[55];
  assign delayMatch_reg_next[57] = delayMatch_reg[56];
  assign delayMatch_reg_next[58] = delayMatch_reg[57];
  assign delayMatch_reg_next[59] = delayMatch_reg[58];
  assign delayMatch_reg_next[60] = delayMatch_reg[59];
  assign delayMatch_reg_next[61] = delayMatch_reg[60];
  assign delayMatch_reg_next[62] = delayMatch_reg[61];
  assign delayMatch_reg_next[63] = delayMatch_reg[62];
  assign delayMatch_reg_next[64] = delayMatch_reg[63];
  assign delayMatch_reg_next[65] = delayMatch_reg[64];
  assign delayMatch_reg_next[66] = delayMatch_reg[65];
  assign delayMatch_reg_next[67] = delayMatch_reg[66];
  assign delayMatch_reg_next[68] = delayMatch_reg[67];
  assign delayMatch_reg_next[69] = delayMatch_reg[68];
  assign delayMatch_reg_next[70] = delayMatch_reg[69];
  assign delayMatch_reg_next[71] = delayMatch_reg[70];
  assign delayMatch_reg_next[72] = delayMatch_reg[71];
  assign delayMatch_reg_next[73] = delayMatch_reg[72];
  assign delayMatch_reg_next[74] = delayMatch_reg[73];
  assign delayMatch_reg_next[75] = delayMatch_reg[74];
  assign delayMatch_reg_next[76] = delayMatch_reg[75];
  assign delayMatch_reg_next[77] = delayMatch_reg[76];
  assign delayMatch_reg_next[78] = delayMatch_reg[77];
  assign delayMatch_reg_next[79] = delayMatch_reg[78];
  assign delayMatch_reg_next[80] = delayMatch_reg[79];
  assign delayMatch_reg_next[81] = delayMatch_reg[80];
  assign delayMatch_reg_next[82] = delayMatch_reg[81];
  assign delayMatch_reg_next[83] = delayMatch_reg[82];
  assign delayMatch_reg_next[84] = delayMatch_reg[83];
  assign delayMatch_reg_next[85] = delayMatch_reg[84];
  assign delayMatch_reg_next[86] = delayMatch_reg[85];
  assign delayMatch_reg_next[87] = delayMatch_reg[86];
  assign delayMatch_reg_next[88] = delayMatch_reg[87];
  assign delayMatch_reg_next[89] = delayMatch_reg[88];
  assign delayMatch_reg_next[90] = delayMatch_reg[89];
  assign delayMatch_reg_next[91] = delayMatch_reg[90];
  assign delayMatch_reg_next[92] = delayMatch_reg[91];
  assign delayMatch_reg_next[93] = delayMatch_reg[92];
  assign delayMatch_reg_next[94] = delayMatch_reg[93];
  assign delayMatch_reg_next[95] = delayMatch_reg[94];
  assign delayMatch_reg_next[96] = delayMatch_reg[95];
  assign delayMatch_reg_next[97] = delayMatch_reg[96];
  assign delayMatch_reg_next[98] = delayMatch_reg[97];
  assign delayMatch_reg_next[99] = delayMatch_reg[98];
  assign delayMatch_reg_next[100] = delayMatch_reg[99];
  assign delayMatch_reg_next[101] = delayMatch_reg[100];
  assign delayMatch_reg_next[102] = delayMatch_reg[101];
  assign delayMatch_reg_next[103] = delayMatch_reg[102];
  assign delayMatch_reg_next[104] = delayMatch_reg[103];
  assign delayMatch_reg_next[105] = delayMatch_reg[104];
  assign delayMatch_reg_next[106] = delayMatch_reg[105];
  assign delayMatch_reg_next[107] = delayMatch_reg[106];
  assign delayMatch_reg_next[108] = delayMatch_reg[107];
  assign delayMatch_reg_next[109] = delayMatch_reg[108];
  assign delayMatch_reg_next[110] = delayMatch_reg[109];
  assign delayMatch_reg_next[111] = delayMatch_reg[110];
  assign delayMatch_reg_next[112] = delayMatch_reg[111];
  assign delayMatch_reg_next[113] = delayMatch_reg[112];
  assign delayMatch_reg_next[114] = delayMatch_reg[113];
  assign delayMatch_reg_next[115] = delayMatch_reg[114];
  assign delayMatch_reg_next[116] = delayMatch_reg[115];
  assign delayMatch_reg_next[117] = delayMatch_reg[116];
  assign delayMatch_reg_next[118] = delayMatch_reg[117];
  assign delayMatch_reg_next[119] = delayMatch_reg[118];



  LoR_Even_block1 u_LoR_Even (.clk(clk),
                              .reset(reset),
                              .enb(enb),
                              .In_LoR_e(In_LoD),  // sfix16_En23
                              .Out_LoR_e(LoR_Even_out1)  // sfix16_En23
                              );
  assign Add_add_cast = {{5{HiR_Even_out1_1[15]}}, HiR_Even_out1_1[15:5]};
  assign Add_out1 = Add_add_cast + LoR_Even_out1;


  HiR_Odd_block1 u_HiR_Odd (.clk(clk),
                            .reset(reset),
                            .enb(enb),
                            .In_HiR_o(In_HiD),  // sfix16_En27
                            .Out_HiR_o(HiR_Odd_out1)  // sfix16_En29
                            );
  always @(posedge clk)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        delayMatch1_reg[0] <= 16'sb0000000000000000;
        delayMatch1_reg[1] <= 16'sb0000000000000000;
        delayMatch1_reg[2] <= 16'sb0000000000000000;
        delayMatch1_reg[3] <= 16'sb0000000000000000;
        delayMatch1_reg[4] <= 16'sb0000000000000000;
        delayMatch1_reg[5] <= 16'sb0000000000000000;
        delayMatch1_reg[6] <= 16'sb0000000000000000;
        delayMatch1_reg[7] <= 16'sb0000000000000000;
        delayMatch1_reg[8] <= 16'sb0000000000000000;
        delayMatch1_reg[9] <= 16'sb0000000000000000;
        delayMatch1_reg[10] <= 16'sb0000000000000000;
        delayMatch1_reg[11] <= 16'sb0000000000000000;
        delayMatch1_reg[12] <= 16'sb0000000000000000;
        delayMatch1_reg[13] <= 16'sb0000000000000000;
        delayMatch1_reg[14] <= 16'sb0000000000000000;
        delayMatch1_reg[15] <= 16'sb0000000000000000;
        delayMatch1_reg[16] <= 16'sb0000000000000000;
        delayMatch1_reg[17] <= 16'sb0000000000000000;
        delayMatch1_reg[18] <= 16'sb0000000000000000;
        delayMatch1_reg[19] <= 16'sb0000000000000000;
        delayMatch1_reg[20] <= 16'sb0000000000000000;
        delayMatch1_reg[21] <= 16'sb0000000000000000;
        delayMatch1_reg[22] <= 16'sb0000000000000000;
        delayMatch1_reg[23] <= 16'sb0000000000000000;
        delayMatch1_reg[24] <= 16'sb0000000000000000;
        delayMatch1_reg[25] <= 16'sb0000000000000000;
        delayMatch1_reg[26] <= 16'sb0000000000000000;
        delayMatch1_reg[27] <= 16'sb0000000000000000;
        delayMatch1_reg[28] <= 16'sb0000000000000000;
        delayMatch1_reg[29] <= 16'sb0000000000000000;
        delayMatch1_reg[30] <= 16'sb0000000000000000;
        delayMatch1_reg[31] <= 16'sb0000000000000000;
        delayMatch1_reg[32] <= 16'sb0000000000000000;
        delayMatch1_reg[33] <= 16'sb0000000000000000;
        delayMatch1_reg[34] <= 16'sb0000000000000000;
        delayMatch1_reg[35] <= 16'sb0000000000000000;
        delayMatch1_reg[36] <= 16'sb0000000000000000;
        delayMatch1_reg[37] <= 16'sb0000000000000000;
        delayMatch1_reg[38] <= 16'sb0000000000000000;
        delayMatch1_reg[39] <= 16'sb0000000000000000;
        delayMatch1_reg[40] <= 16'sb0000000000000000;
        delayMatch1_reg[41] <= 16'sb0000000000000000;
        delayMatch1_reg[42] <= 16'sb0000000000000000;
        delayMatch1_reg[43] <= 16'sb0000000000000000;
        delayMatch1_reg[44] <= 16'sb0000000000000000;
        delayMatch1_reg[45] <= 16'sb0000000000000000;
        delayMatch1_reg[46] <= 16'sb0000000000000000;
        delayMatch1_reg[47] <= 16'sb0000000000000000;
        delayMatch1_reg[48] <= 16'sb0000000000000000;
        delayMatch1_reg[49] <= 16'sb0000000000000000;
        delayMatch1_reg[50] <= 16'sb0000000000000000;
        delayMatch1_reg[51] <= 16'sb0000000000000000;
        delayMatch1_reg[52] <= 16'sb0000000000000000;
        delayMatch1_reg[53] <= 16'sb0000000000000000;
        delayMatch1_reg[54] <= 16'sb0000000000000000;
        delayMatch1_reg[55] <= 16'sb0000000000000000;
        delayMatch1_reg[56] <= 16'sb0000000000000000;
        delayMatch1_reg[57] <= 16'sb0000000000000000;
        delayMatch1_reg[58] <= 16'sb0000000000000000;
        delayMatch1_reg[59] <= 16'sb0000000000000000;
        delayMatch1_reg[60] <= 16'sb0000000000000000;
        delayMatch1_reg[61] <= 16'sb0000000000000000;
        delayMatch1_reg[62] <= 16'sb0000000000000000;
        delayMatch1_reg[63] <= 16'sb0000000000000000;
        delayMatch1_reg[64] <= 16'sb0000000000000000;
        delayMatch1_reg[65] <= 16'sb0000000000000000;
        delayMatch1_reg[66] <= 16'sb0000000000000000;
        delayMatch1_reg[67] <= 16'sb0000000000000000;
        delayMatch1_reg[68] <= 16'sb0000000000000000;
        delayMatch1_reg[69] <= 16'sb0000000000000000;
        delayMatch1_reg[70] <= 16'sb0000000000000000;
        delayMatch1_reg[71] <= 16'sb0000000000000000;
        delayMatch1_reg[72] <= 16'sb0000000000000000;
        delayMatch1_reg[73] <= 16'sb0000000000000000;
        delayMatch1_reg[74] <= 16'sb0000000000000000;
        delayMatch1_reg[75] <= 16'sb0000000000000000;
        delayMatch1_reg[76] <= 16'sb0000000000000000;
        delayMatch1_reg[77] <= 16'sb0000000000000000;
        delayMatch1_reg[78] <= 16'sb0000000000000000;
        delayMatch1_reg[79] <= 16'sb0000000000000000;
        delayMatch1_reg[80] <= 16'sb0000000000000000;
        delayMatch1_reg[81] <= 16'sb0000000000000000;
        delayMatch1_reg[82] <= 16'sb0000000000000000;
        delayMatch1_reg[83] <= 16'sb0000000000000000;
        delayMatch1_reg[84] <= 16'sb0000000000000000;
        delayMatch1_reg[85] <= 16'sb0000000000000000;
        delayMatch1_reg[86] <= 16'sb0000000000000000;
        delayMatch1_reg[87] <= 16'sb0000000000000000;
        delayMatch1_reg[88] <= 16'sb0000000000000000;
        delayMatch1_reg[89] <= 16'sb0000000000000000;
        delayMatch1_reg[90] <= 16'sb0000000000000000;
        delayMatch1_reg[91] <= 16'sb0000000000000000;
        delayMatch1_reg[92] <= 16'sb0000000000000000;
        delayMatch1_reg[93] <= 16'sb0000000000000000;
        delayMatch1_reg[94] <= 16'sb0000000000000000;
        delayMatch1_reg[95] <= 16'sb0000000000000000;
        delayMatch1_reg[96] <= 16'sb0000000000000000;
        delayMatch1_reg[97] <= 16'sb0000000000000000;
        delayMatch1_reg[98] <= 16'sb0000000000000000;
        delayMatch1_reg[99] <= 16'sb0000000000000000;
        delayMatch1_reg[100] <= 16'sb0000000000000000;
        delayMatch1_reg[101] <= 16'sb0000000000000000;
        delayMatch1_reg[102] <= 16'sb0000000000000000;
        delayMatch1_reg[103] <= 16'sb0000000000000000;
        delayMatch1_reg[104] <= 16'sb0000000000000000;
        delayMatch1_reg[105] <= 16'sb0000000000000000;
        delayMatch1_reg[106] <= 16'sb0000000000000000;
        delayMatch1_reg[107] <= 16'sb0000000000000000;
        delayMatch1_reg[108] <= 16'sb0000000000000000;
        delayMatch1_reg[109] <= 16'sb0000000000000000;
        delayMatch1_reg[110] <= 16'sb0000000000000000;
        delayMatch1_reg[111] <= 16'sb0000000000000000;
        delayMatch1_reg[112] <= 16'sb0000000000000000;
        delayMatch1_reg[113] <= 16'sb0000000000000000;
        delayMatch1_reg[114] <= 16'sb0000000000000000;
        delayMatch1_reg[115] <= 16'sb0000000000000000;
        delayMatch1_reg[116] <= 16'sb0000000000000000;
        delayMatch1_reg[117] <= 16'sb0000000000000000;
        delayMatch1_reg[118] <= 16'sb0000000000000000;
        delayMatch1_reg[119] <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch1_reg[0] <= delayMatch1_reg_next[0];
          delayMatch1_reg[1] <= delayMatch1_reg_next[1];
          delayMatch1_reg[2] <= delayMatch1_reg_next[2];
          delayMatch1_reg[3] <= delayMatch1_reg_next[3];
          delayMatch1_reg[4] <= delayMatch1_reg_next[4];
          delayMatch1_reg[5] <= delayMatch1_reg_next[5];
          delayMatch1_reg[6] <= delayMatch1_reg_next[6];
          delayMatch1_reg[7] <= delayMatch1_reg_next[7];
          delayMatch1_reg[8] <= delayMatch1_reg_next[8];
          delayMatch1_reg[9] <= delayMatch1_reg_next[9];
          delayMatch1_reg[10] <= delayMatch1_reg_next[10];
          delayMatch1_reg[11] <= delayMatch1_reg_next[11];
          delayMatch1_reg[12] <= delayMatch1_reg_next[12];
          delayMatch1_reg[13] <= delayMatch1_reg_next[13];
          delayMatch1_reg[14] <= delayMatch1_reg_next[14];
          delayMatch1_reg[15] <= delayMatch1_reg_next[15];
          delayMatch1_reg[16] <= delayMatch1_reg_next[16];
          delayMatch1_reg[17] <= delayMatch1_reg_next[17];
          delayMatch1_reg[18] <= delayMatch1_reg_next[18];
          delayMatch1_reg[19] <= delayMatch1_reg_next[19];
          delayMatch1_reg[20] <= delayMatch1_reg_next[20];
          delayMatch1_reg[21] <= delayMatch1_reg_next[21];
          delayMatch1_reg[22] <= delayMatch1_reg_next[22];
          delayMatch1_reg[23] <= delayMatch1_reg_next[23];
          delayMatch1_reg[24] <= delayMatch1_reg_next[24];
          delayMatch1_reg[25] <= delayMatch1_reg_next[25];
          delayMatch1_reg[26] <= delayMatch1_reg_next[26];
          delayMatch1_reg[27] <= delayMatch1_reg_next[27];
          delayMatch1_reg[28] <= delayMatch1_reg_next[28];
          delayMatch1_reg[29] <= delayMatch1_reg_next[29];
          delayMatch1_reg[30] <= delayMatch1_reg_next[30];
          delayMatch1_reg[31] <= delayMatch1_reg_next[31];
          delayMatch1_reg[32] <= delayMatch1_reg_next[32];
          delayMatch1_reg[33] <= delayMatch1_reg_next[33];
          delayMatch1_reg[34] <= delayMatch1_reg_next[34];
          delayMatch1_reg[35] <= delayMatch1_reg_next[35];
          delayMatch1_reg[36] <= delayMatch1_reg_next[36];
          delayMatch1_reg[37] <= delayMatch1_reg_next[37];
          delayMatch1_reg[38] <= delayMatch1_reg_next[38];
          delayMatch1_reg[39] <= delayMatch1_reg_next[39];
          delayMatch1_reg[40] <= delayMatch1_reg_next[40];
          delayMatch1_reg[41] <= delayMatch1_reg_next[41];
          delayMatch1_reg[42] <= delayMatch1_reg_next[42];
          delayMatch1_reg[43] <= delayMatch1_reg_next[43];
          delayMatch1_reg[44] <= delayMatch1_reg_next[44];
          delayMatch1_reg[45] <= delayMatch1_reg_next[45];
          delayMatch1_reg[46] <= delayMatch1_reg_next[46];
          delayMatch1_reg[47] <= delayMatch1_reg_next[47];
          delayMatch1_reg[48] <= delayMatch1_reg_next[48];
          delayMatch1_reg[49] <= delayMatch1_reg_next[49];
          delayMatch1_reg[50] <= delayMatch1_reg_next[50];
          delayMatch1_reg[51] <= delayMatch1_reg_next[51];
          delayMatch1_reg[52] <= delayMatch1_reg_next[52];
          delayMatch1_reg[53] <= delayMatch1_reg_next[53];
          delayMatch1_reg[54] <= delayMatch1_reg_next[54];
          delayMatch1_reg[55] <= delayMatch1_reg_next[55];
          delayMatch1_reg[56] <= delayMatch1_reg_next[56];
          delayMatch1_reg[57] <= delayMatch1_reg_next[57];
          delayMatch1_reg[58] <= delayMatch1_reg_next[58];
          delayMatch1_reg[59] <= delayMatch1_reg_next[59];
          delayMatch1_reg[60] <= delayMatch1_reg_next[60];
          delayMatch1_reg[61] <= delayMatch1_reg_next[61];
          delayMatch1_reg[62] <= delayMatch1_reg_next[62];
          delayMatch1_reg[63] <= delayMatch1_reg_next[63];
          delayMatch1_reg[64] <= delayMatch1_reg_next[64];
          delayMatch1_reg[65] <= delayMatch1_reg_next[65];
          delayMatch1_reg[66] <= delayMatch1_reg_next[66];
          delayMatch1_reg[67] <= delayMatch1_reg_next[67];
          delayMatch1_reg[68] <= delayMatch1_reg_next[68];
          delayMatch1_reg[69] <= delayMatch1_reg_next[69];
          delayMatch1_reg[70] <= delayMatch1_reg_next[70];
          delayMatch1_reg[71] <= delayMatch1_reg_next[71];
          delayMatch1_reg[72] <= delayMatch1_reg_next[72];
          delayMatch1_reg[73] <= delayMatch1_reg_next[73];
          delayMatch1_reg[74] <= delayMatch1_reg_next[74];
          delayMatch1_reg[75] <= delayMatch1_reg_next[75];
          delayMatch1_reg[76] <= delayMatch1_reg_next[76];
          delayMatch1_reg[77] <= delayMatch1_reg_next[77];
          delayMatch1_reg[78] <= delayMatch1_reg_next[78];
          delayMatch1_reg[79] <= delayMatch1_reg_next[79];
          delayMatch1_reg[80] <= delayMatch1_reg_next[80];
          delayMatch1_reg[81] <= delayMatch1_reg_next[81];
          delayMatch1_reg[82] <= delayMatch1_reg_next[82];
          delayMatch1_reg[83] <= delayMatch1_reg_next[83];
          delayMatch1_reg[84] <= delayMatch1_reg_next[84];
          delayMatch1_reg[85] <= delayMatch1_reg_next[85];
          delayMatch1_reg[86] <= delayMatch1_reg_next[86];
          delayMatch1_reg[87] <= delayMatch1_reg_next[87];
          delayMatch1_reg[88] <= delayMatch1_reg_next[88];
          delayMatch1_reg[89] <= delayMatch1_reg_next[89];
          delayMatch1_reg[90] <= delayMatch1_reg_next[90];
          delayMatch1_reg[91] <= delayMatch1_reg_next[91];
          delayMatch1_reg[92] <= delayMatch1_reg_next[92];
          delayMatch1_reg[93] <= delayMatch1_reg_next[93];
          delayMatch1_reg[94] <= delayMatch1_reg_next[94];
          delayMatch1_reg[95] <= delayMatch1_reg_next[95];
          delayMatch1_reg[96] <= delayMatch1_reg_next[96];
          delayMatch1_reg[97] <= delayMatch1_reg_next[97];
          delayMatch1_reg[98] <= delayMatch1_reg_next[98];
          delayMatch1_reg[99] <= delayMatch1_reg_next[99];
          delayMatch1_reg[100] <= delayMatch1_reg_next[100];
          delayMatch1_reg[101] <= delayMatch1_reg_next[101];
          delayMatch1_reg[102] <= delayMatch1_reg_next[102];
          delayMatch1_reg[103] <= delayMatch1_reg_next[103];
          delayMatch1_reg[104] <= delayMatch1_reg_next[104];
          delayMatch1_reg[105] <= delayMatch1_reg_next[105];
          delayMatch1_reg[106] <= delayMatch1_reg_next[106];
          delayMatch1_reg[107] <= delayMatch1_reg_next[107];
          delayMatch1_reg[108] <= delayMatch1_reg_next[108];
          delayMatch1_reg[109] <= delayMatch1_reg_next[109];
          delayMatch1_reg[110] <= delayMatch1_reg_next[110];
          delayMatch1_reg[111] <= delayMatch1_reg_next[111];
          delayMatch1_reg[112] <= delayMatch1_reg_next[112];
          delayMatch1_reg[113] <= delayMatch1_reg_next[113];
          delayMatch1_reg[114] <= delayMatch1_reg_next[114];
          delayMatch1_reg[115] <= delayMatch1_reg_next[115];
          delayMatch1_reg[116] <= delayMatch1_reg_next[116];
          delayMatch1_reg[117] <= delayMatch1_reg_next[117];
          delayMatch1_reg[118] <= delayMatch1_reg_next[118];
          delayMatch1_reg[119] <= delayMatch1_reg_next[119];
        end
      end
    end

  assign HiR_Odd_out1_1 = delayMatch1_reg[119];
  assign delayMatch1_reg_next[0] = HiR_Odd_out1;
  assign delayMatch1_reg_next[1] = delayMatch1_reg[0];
  assign delayMatch1_reg_next[2] = delayMatch1_reg[1];
  assign delayMatch1_reg_next[3] = delayMatch1_reg[2];
  assign delayMatch1_reg_next[4] = delayMatch1_reg[3];
  assign delayMatch1_reg_next[5] = delayMatch1_reg[4];
  assign delayMatch1_reg_next[6] = delayMatch1_reg[5];
  assign delayMatch1_reg_next[7] = delayMatch1_reg[6];
  assign delayMatch1_reg_next[8] = delayMatch1_reg[7];
  assign delayMatch1_reg_next[9] = delayMatch1_reg[8];
  assign delayMatch1_reg_next[10] = delayMatch1_reg[9];
  assign delayMatch1_reg_next[11] = delayMatch1_reg[10];
  assign delayMatch1_reg_next[12] = delayMatch1_reg[11];
  assign delayMatch1_reg_next[13] = delayMatch1_reg[12];
  assign delayMatch1_reg_next[14] = delayMatch1_reg[13];
  assign delayMatch1_reg_next[15] = delayMatch1_reg[14];
  assign delayMatch1_reg_next[16] = delayMatch1_reg[15];
  assign delayMatch1_reg_next[17] = delayMatch1_reg[16];
  assign delayMatch1_reg_next[18] = delayMatch1_reg[17];
  assign delayMatch1_reg_next[19] = delayMatch1_reg[18];
  assign delayMatch1_reg_next[20] = delayMatch1_reg[19];
  assign delayMatch1_reg_next[21] = delayMatch1_reg[20];
  assign delayMatch1_reg_next[22] = delayMatch1_reg[21];
  assign delayMatch1_reg_next[23] = delayMatch1_reg[22];
  assign delayMatch1_reg_next[24] = delayMatch1_reg[23];
  assign delayMatch1_reg_next[25] = delayMatch1_reg[24];
  assign delayMatch1_reg_next[26] = delayMatch1_reg[25];
  assign delayMatch1_reg_next[27] = delayMatch1_reg[26];
  assign delayMatch1_reg_next[28] = delayMatch1_reg[27];
  assign delayMatch1_reg_next[29] = delayMatch1_reg[28];
  assign delayMatch1_reg_next[30] = delayMatch1_reg[29];
  assign delayMatch1_reg_next[31] = delayMatch1_reg[30];
  assign delayMatch1_reg_next[32] = delayMatch1_reg[31];
  assign delayMatch1_reg_next[33] = delayMatch1_reg[32];
  assign delayMatch1_reg_next[34] = delayMatch1_reg[33];
  assign delayMatch1_reg_next[35] = delayMatch1_reg[34];
  assign delayMatch1_reg_next[36] = delayMatch1_reg[35];
  assign delayMatch1_reg_next[37] = delayMatch1_reg[36];
  assign delayMatch1_reg_next[38] = delayMatch1_reg[37];
  assign delayMatch1_reg_next[39] = delayMatch1_reg[38];
  assign delayMatch1_reg_next[40] = delayMatch1_reg[39];
  assign delayMatch1_reg_next[41] = delayMatch1_reg[40];
  assign delayMatch1_reg_next[42] = delayMatch1_reg[41];
  assign delayMatch1_reg_next[43] = delayMatch1_reg[42];
  assign delayMatch1_reg_next[44] = delayMatch1_reg[43];
  assign delayMatch1_reg_next[45] = delayMatch1_reg[44];
  assign delayMatch1_reg_next[46] = delayMatch1_reg[45];
  assign delayMatch1_reg_next[47] = delayMatch1_reg[46];
  assign delayMatch1_reg_next[48] = delayMatch1_reg[47];
  assign delayMatch1_reg_next[49] = delayMatch1_reg[48];
  assign delayMatch1_reg_next[50] = delayMatch1_reg[49];
  assign delayMatch1_reg_next[51] = delayMatch1_reg[50];
  assign delayMatch1_reg_next[52] = delayMatch1_reg[51];
  assign delayMatch1_reg_next[53] = delayMatch1_reg[52];
  assign delayMatch1_reg_next[54] = delayMatch1_reg[53];
  assign delayMatch1_reg_next[55] = delayMatch1_reg[54];
  assign delayMatch1_reg_next[56] = delayMatch1_reg[55];
  assign delayMatch1_reg_next[57] = delayMatch1_reg[56];
  assign delayMatch1_reg_next[58] = delayMatch1_reg[57];
  assign delayMatch1_reg_next[59] = delayMatch1_reg[58];
  assign delayMatch1_reg_next[60] = delayMatch1_reg[59];
  assign delayMatch1_reg_next[61] = delayMatch1_reg[60];
  assign delayMatch1_reg_next[62] = delayMatch1_reg[61];
  assign delayMatch1_reg_next[63] = delayMatch1_reg[62];
  assign delayMatch1_reg_next[64] = delayMatch1_reg[63];
  assign delayMatch1_reg_next[65] = delayMatch1_reg[64];
  assign delayMatch1_reg_next[66] = delayMatch1_reg[65];
  assign delayMatch1_reg_next[67] = delayMatch1_reg[66];
  assign delayMatch1_reg_next[68] = delayMatch1_reg[67];
  assign delayMatch1_reg_next[69] = delayMatch1_reg[68];
  assign delayMatch1_reg_next[70] = delayMatch1_reg[69];
  assign delayMatch1_reg_next[71] = delayMatch1_reg[70];
  assign delayMatch1_reg_next[72] = delayMatch1_reg[71];
  assign delayMatch1_reg_next[73] = delayMatch1_reg[72];
  assign delayMatch1_reg_next[74] = delayMatch1_reg[73];
  assign delayMatch1_reg_next[75] = delayMatch1_reg[74];
  assign delayMatch1_reg_next[76] = delayMatch1_reg[75];
  assign delayMatch1_reg_next[77] = delayMatch1_reg[76];
  assign delayMatch1_reg_next[78] = delayMatch1_reg[77];
  assign delayMatch1_reg_next[79] = delayMatch1_reg[78];
  assign delayMatch1_reg_next[80] = delayMatch1_reg[79];
  assign delayMatch1_reg_next[81] = delayMatch1_reg[80];
  assign delayMatch1_reg_next[82] = delayMatch1_reg[81];
  assign delayMatch1_reg_next[83] = delayMatch1_reg[82];
  assign delayMatch1_reg_next[84] = delayMatch1_reg[83];
  assign delayMatch1_reg_next[85] = delayMatch1_reg[84];
  assign delayMatch1_reg_next[86] = delayMatch1_reg[85];
  assign delayMatch1_reg_next[87] = delayMatch1_reg[86];
  assign delayMatch1_reg_next[88] = delayMatch1_reg[87];
  assign delayMatch1_reg_next[89] = delayMatch1_reg[88];
  assign delayMatch1_reg_next[90] = delayMatch1_reg[89];
  assign delayMatch1_reg_next[91] = delayMatch1_reg[90];
  assign delayMatch1_reg_next[92] = delayMatch1_reg[91];
  assign delayMatch1_reg_next[93] = delayMatch1_reg[92];
  assign delayMatch1_reg_next[94] = delayMatch1_reg[93];
  assign delayMatch1_reg_next[95] = delayMatch1_reg[94];
  assign delayMatch1_reg_next[96] = delayMatch1_reg[95];
  assign delayMatch1_reg_next[97] = delayMatch1_reg[96];
  assign delayMatch1_reg_next[98] = delayMatch1_reg[97];
  assign delayMatch1_reg_next[99] = delayMatch1_reg[98];
  assign delayMatch1_reg_next[100] = delayMatch1_reg[99];
  assign delayMatch1_reg_next[101] = delayMatch1_reg[100];
  assign delayMatch1_reg_next[102] = delayMatch1_reg[101];
  assign delayMatch1_reg_next[103] = delayMatch1_reg[102];
  assign delayMatch1_reg_next[104] = delayMatch1_reg[103];
  assign delayMatch1_reg_next[105] = delayMatch1_reg[104];
  assign delayMatch1_reg_next[106] = delayMatch1_reg[105];
  assign delayMatch1_reg_next[107] = delayMatch1_reg[106];
  assign delayMatch1_reg_next[108] = delayMatch1_reg[107];
  assign delayMatch1_reg_next[109] = delayMatch1_reg[108];
  assign delayMatch1_reg_next[110] = delayMatch1_reg[109];
  assign delayMatch1_reg_next[111] = delayMatch1_reg[110];
  assign delayMatch1_reg_next[112] = delayMatch1_reg[111];
  assign delayMatch1_reg_next[113] = delayMatch1_reg[112];
  assign delayMatch1_reg_next[114] = delayMatch1_reg[113];
  assign delayMatch1_reg_next[115] = delayMatch1_reg[114];
  assign delayMatch1_reg_next[116] = delayMatch1_reg[115];
  assign delayMatch1_reg_next[117] = delayMatch1_reg[116];
  assign delayMatch1_reg_next[118] = delayMatch1_reg[117];
  assign delayMatch1_reg_next[119] = delayMatch1_reg[118];



  LoR_Odd_block1 u_LoR_Odd (.clk(clk),
                            .reset(reset),
                            .enb(enb),
                            .In_LoR_o(In_LoD),  // sfix16_En23
                            .Out_HiR_o(LoR_Odd_out1)  // sfix16_En23
                            );
  assign Add1_add_cast = {{6{HiR_Odd_out1_1[15]}}, HiR_Odd_out1_1[15:6]};
  assign Add1_out1 = Add1_add_cast + LoR_Odd_out1;


  always @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Add1_out1;
        end
      end
    end


  assign Add2_add_cast = {Add_out1[15], Add_out1[15:1]};
  assign Add2_add_cast_1 = {Delay2_out1[15], Delay2_out1[15:1]};
  assign Add2_out1 = Add2_add_cast + Add2_add_cast_1;


  always @(posedge clk)
    begin : HwModeRegister1_process
      if (reset == 1'b1) begin
        Add2_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Add2_out1_1 <= Add2_out1;
        end
      end
    end



  assign Gain_cast = {1'b0, kconst_1};
  assign Gain_mul_temp = Gain_cast * Add2_out1_1;
  assign Gain_cast_1 = Gain_mul_temp[31:0];
  assign Gain_out1 = Gain_cast_1[31:16];


  always @(posedge clk)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Gain_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Gain_out1_1 <= Gain_out1;
        end
      end
    end


  assign Out = Gain_out1_1;

endmodule  // alpha1st_Level_Recon2

