open_system('gm_final_heart_coif1_3_Level_fixed');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon', 'user2');
annotate_port('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon', 0, 1, 'cp : 14.634 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/HiR_Even1', 'user2');
annotate_port('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/HiR_Even1', 0, 1, 'cp : 4.759 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/Add', 'user2');
annotate_port('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/Add', 0, 1, 'cp : 9.518 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/Add2', 'user2');
annotate_port('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/Add2', 0, 1, 'cp : 14.277 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/HwModeRegister1', 'user1');
annotate_port('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/HwModeRegister1', 1, 1, 'cp : 14.634 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/HiR_Even1/Add', 'user2');
annotate_port('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/HiR_Even1/Add', 0, 1, 'cp : 4.759 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/HiR_Even1/PipelineRegister', 'user1');
annotate_port('gm_final_heart_coif1_3_Level_fixed/DWT_coif1_3_Level/1st_Level_Recon/HiR_Even1/PipelineRegister', 0, 1, 'cp : 0 ns');
