// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\db4_2_Level_fixdt\LoR_Odd_block.v
// Created: 2024-04-18 14:13:01
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LoR_Odd_block
// Source Path: db4_2_Level_fixdt/DWT_db4_2_Level/2nd_Level_Recon/LoR_Odd
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LoR_Odd_block
          (clk,
           reset,
           enb,
           In_HiR_e,
           Out_HiR_e);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In_HiR_e;  // sfix16_En23
  output  signed [15:0] Out_HiR_e;  // sfix16_En23


  wire [15:0] LoR_1_out1;  // ufix16_En16
  reg [15:0] LoR_1_out1_1;  // ufix16_En16
  reg signed [15:0] In_HiR_e_1;  // sfix16_En23
  wire signed [16:0] Multiply_cast;  // sfix17_En16
  wire signed [32:0] Multiply_mul_temp;  // sfix33_En39
  wire signed [31:0] Multiply_cast_1;  // sfix32_En39
  wire signed [15:0] Multiply_out1;  // sfix16_En23
  reg signed [15:0] Multiply_out1_1;  // sfix16_En23
  wire signed [15:0] LoR_3_out1;  // sfix16_En20
  reg signed [15:0] LoR_3_out1_1;  // sfix16_En20
  reg signed [15:0] Rate_Transition_out1;  // sfix16_En23
  wire signed [31:0] Multiply1_mul_temp;  // sfix32_En43
  wire signed [15:0] Multiply1_out1;  // sfix16_En28
  reg signed [15:0] Multiply1_out1_1;  // sfix16_En28
  wire [15:0] LoR_5_out1;  // ufix16_En21
  reg [15:0] LoR_5_out1_1;  // ufix16_En21
  reg signed [15:0] Rate_Transition1_out1;  // sfix16_En23
  wire signed [16:0] Multiply2_cast;  // sfix17_En21
  wire signed [32:0] Multiply2_mul_temp;  // sfix33_En44
  wire signed [31:0] Multiply2_cast_1;  // sfix32_En44
  wire signed [15:0] Multiply2_out1;  // sfix16_En28
  reg signed [15:0] Multiply2_out1_1;  // sfix16_En28
  wire signed [15:0] LoR_7_out1;  // sfix16_En21
  reg signed [15:0] LoR_7_out1_1;  // sfix16_En21
  reg signed [15:0] Rate_Transition2_out1;  // sfix16_En23
  wire signed [31:0] Multiply3_mul_temp;  // sfix32_En44
  wire signed [15:0] Multiply3_out1;  // sfix16_En29
  reg signed [15:0] delayMatch_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch_reg_next [0:1];  // sfix16_En29 [2]
  wire signed [15:0] Multiply3_out1_1;  // sfix16_En29
  wire signed [15:0] Add2_add_cast;  // sfix16_En28
  wire signed [15:0] Add2_out1;  // sfix16_En28
  reg signed [15:0] Delay2_out1;  // sfix16_En28
  wire signed [15:0] Add1_add_temp;  // sfix16_En28
  wire signed [15:0] Add1_out1;  // sfix16_En29
  reg signed [15:0] Delay3_out1;  // sfix16_En29
  wire signed [15:0] Add_add_cast;  // sfix16_En23
  wire signed [15:0] Add_out1;  // sfix16_En23


  assign LoR_1_out1 = 16'b1011011100000000;


  always @(posedge clk)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        LoR_1_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoR_1_out1_1 <= LoR_1_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_process
      if (reset == 1'b1) begin
        In_HiR_e_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          In_HiR_e_1 <= In_HiR_e;
        end
      end
    end


  assign Multiply_cast = {1'b0, LoR_1_out1_1};
  assign Multiply_mul_temp = Multiply_cast * In_HiR_e_1;
  assign Multiply_cast_1 = Multiply_mul_temp[31:0];
  assign Multiply_out1 = Multiply_cast_1[31:16];


  always @(posedge clk)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Multiply_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply_out1_1 <= Multiply_out1;
        end
      end
    end



  assign LoR_3_out1 = 16'sb1000110101100001;


  always @(posedge clk)
    begin : HwModeRegister2_process
      if (reset == 1'b1) begin
        LoR_3_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          LoR_3_out1_1 <= LoR_3_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        Rate_Transition_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition_out1 <= In_HiR_e_1;
        end
      end
    end


  assign Multiply1_mul_temp = LoR_3_out1_1 * Rate_Transition_out1;
  assign Multiply1_out1 = Multiply1_mul_temp[30:15];


  always @(posedge clk)
    begin : PipelineRegister1_process
      if (reset == 1'b1) begin
        Multiply1_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply1_out1_1 <= Multiply1_out1;
        end
      end
    end



  assign LoR_5_out1 = 16'b1111110010100111;


  always @(posedge clk)
    begin : HwModeRegister4_process
      if (reset == 1'b1) begin
        LoR_5_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoR_5_out1_1 <= LoR_5_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_2_process
      if (reset == 1'b1) begin
        Rate_Transition1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition1_out1 <= Rate_Transition_out1;
        end
      end
    end


  assign Multiply2_cast = {1'b0, LoR_5_out1_1};
  assign Multiply2_mul_temp = Multiply2_cast * Rate_Transition1_out1;
  assign Multiply2_cast_1 = Multiply2_mul_temp[31:0];
  assign Multiply2_out1 = Multiply2_cast_1[31:16];


  always @(posedge clk)
    begin : PipelineRegister2_process
      if (reset == 1'b1) begin
        Multiply2_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply2_out1_1 <= Multiply2_out1;
        end
      end
    end



  assign LoR_7_out1 = 16'sb1010100100110000;


  always @(posedge clk)
    begin : HwModeRegister6_process
      if (reset == 1'b1) begin
        LoR_7_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          LoR_7_out1_1 <= LoR_7_out1;
        end
      end
    end



  always @(posedge clk)
    begin : HwModeRegister7_process
      if (reset == 1'b1) begin
        Rate_Transition2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition2_out1 <= Rate_Transition1_out1;
        end
      end
    end



  assign Multiply3_mul_temp = LoR_7_out1_1 * Rate_Transition2_out1;
  assign Multiply3_out1 = Multiply3_mul_temp[30:15];


  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 16'sb0000000000000000;
        delayMatch_reg[1] <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
        end
      end
    end

  assign Multiply3_out1_1 = delayMatch_reg[1];
  assign delayMatch_reg_next[0] = Multiply3_out1;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];



  assign Add2_add_cast = {Multiply3_out1_1[15], Multiply3_out1_1[15:1]};
  assign Add2_out1 = Multiply2_out1_1 + Add2_add_cast;


  always @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Add2_out1;
        end
      end
    end


  assign Add1_add_temp = Multiply1_out1_1 + Delay2_out1;
  assign Add1_out1 = {Add1_add_temp[14:0], 1'b0};


  always @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Add1_out1;
        end
      end
    end


  assign Add_add_cast = {{6{Delay3_out1[15]}}, Delay3_out1[15:6]};
  assign Add_out1 = Multiply_out1_1 + Add_add_cast;


  assign Out_HiR_e = Add_out1;

endmodule  // LoR_Odd_block

