// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\db3_3_Level_fixdt\Data_Sorter18.v
// Created: 2024-04-17 22:28:38
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Data_Sorter18
// Source Path: db3_3_Level_fixdt/DWT_db3_3_Level/Threshold_Estimator/Median2/Data_Sorter18
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Data_Sorter18
          (clk,
           reset,
           enb,
           Signal1,
           Signal2,
           High_Data);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] Signal1;  // ufix16_En27
  input   [15:0] Signal2;  // ufix16_En27
  output  [15:0] High_Data;  // ufix16_En27


  wire Relational_Operator2_relop1;
  wire [15:0] Data_Sorter_Switch_out1;  // ufix16_En27
  reg [15:0] Delay1_out1;  // ufix16_En27


  assign Relational_Operator2_relop1 = Signal1 < Signal2;


  assign Data_Sorter_Switch_out1 = (Relational_Operator2_relop1 == 1'b0 ? Signal1 :
              Signal1);


  always @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Data_Sorter_Switch_out1;
        end
      end
    end


  assign High_Data = Delay1_out1;

endmodule  // Data_Sorter18

