// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\db2_3_Level_fixdt\LoR_Even.v
// Created: 2024-04-17 20:03:41
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LoR_Even
// Source Path: db2_3_Level_fixdt/DWT_db2_3level/1st_Level_Recon/LoR_Even
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LoR_Even
          (clk,
           reset,
           enb,
           In_LoR_e,
           Out_LoR_e);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] In_LoR_e;  // ufix16_En24
  output  [15:0] Out_LoR_e;  // ufix16_En24


  wire [15:0] Constant8_out1;  // ufix16_En17
  reg [15:0] Constant8_out1_1;  // ufix16_En17
  reg [15:0] In_LoR_e_1;  // ufix16_En24
  wire [31:0] Multiply_mul_temp;  // ufix32_En41
  wire [15:0] Multiply_out1;  // ufix16_En25
  reg [15:0] Multiply_out1_1;  // ufix16_En25
  wire [15:0] Constant10_out1;  // ufix16_En18
  reg [15:0] Constant10_out1_1;  // ufix16_En18
  reg [15:0] Rate_Transition_out1;  // ufix16_En24
  wire [31:0] Multiply1_mul_temp;  // ufix32_En42
  wire [15:0] Multiply1_out1;  // ufix16_En26
  reg [15:0] delayMatch_reg [0:1];  // ufix16 [2]
  wire [15:0] delayMatch_reg_next [0:1];  // ufix16_En26 [2]
  wire [15:0] Multiply1_out1_1;  // ufix16_En26
  wire [15:0] Add_add_cast;  // ufix16_En24
  wire [15:0] Add_add_cast_1;  // ufix16_En24
  wire [15:0] Add_out1;  // ufix16_En24


  assign Constant8_out1 = 16'b1111011101000111;


  always @(posedge clk)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        Constant8_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Constant8_out1_1 <= Constant8_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_process
      if (reset == 1'b1) begin
        In_LoR_e_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          In_LoR_e_1 <= In_LoR_e;
        end
      end
    end


  assign Multiply_mul_temp = Constant8_out1_1 * In_LoR_e_1;
  assign Multiply_out1 = Multiply_mul_temp[31:16];


  always @(posedge clk)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Multiply_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply_out1_1 <= Multiply_out1;
        end
      end
    end



  assign Constant10_out1 = 16'b1110010110000110;


  always @(posedge clk)
    begin : HwModeRegister2_process
      if (reset == 1'b1) begin
        Constant10_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Constant10_out1_1 <= Constant10_out1;
        end
      end
    end



  always @(posedge clk)
    begin : HwModeRegister3_process
      if (reset == 1'b1) begin
        Rate_Transition_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition_out1 <= In_LoR_e_1;
        end
      end
    end



  assign Multiply1_mul_temp = Constant10_out1_1 * Rate_Transition_out1;
  assign Multiply1_out1 = Multiply1_mul_temp[31:16];


  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 16'b0000000000000000;
        delayMatch_reg[1] <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
        end
      end
    end

  assign Multiply1_out1_1 = delayMatch_reg[1];
  assign delayMatch_reg_next[0] = Multiply1_out1;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];



  assign Add_add_cast = {1'b0, Multiply_out1_1[15:1]};
  assign Add_add_cast_1 = {2'b0, Multiply1_out1_1[15:2]};
  assign Add_out1 = Add_add_cast + Add_add_cast_1;


  assign Out_LoR_e = Add_out1;

endmodule  // LoR_Even

