// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\final_heart_sym2_level3_hdl\DWT_Sym2_Level3_tb.v
// Created: 2024-04-17 12:03:21
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 2.26757e-05
// Target subsystem base rate: 2.26757e-05
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        2.26757e-05
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        2.26757e-05
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DWT_Sym2_Level3_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DWT_Sym2_Level3_tb;



  reg  clk;
  reg  reset;
  wire clk_enable;
  wire Out1_done;  // ufix1
  wire ce_out;
  wire Out1_done_enb;  // ufix1
  reg [18:0] Out1_addr;  // ufix19
  wire Out1_active;  // ufix1
  reg [18:0] Data_Type_Conversion_out1_addr;  // ufix19
  wire Data_Type_Conversion_out1_active;  // ufix1
  reg  tb_enb_delay;
  wire Data_Type_Conversion_out1_enb;  // ufix1
  wire [18:0] Data_Type_Conversion_out1_addr_delay_1;  // ufix19
  reg signed [31:0] fp_In1;  // sfix32
  reg [15:0] rawData_In1;  // ufix16_En23
  reg signed [31:0] status_In1;  // sfix32
  reg [15:0] holdData_In1;  // ufix16_En23
  reg [15:0] In1_offset;  // ufix16_En23
  wire [15:0] In1;  // ufix16_En23
  reg  check1_done;  // ufix1
  wire snkDonen;
  wire resetn;
  wire tb_enb;
  wire notDone;
  wire signed [15:0] Out1;  // sfix16_En22
  wire Out1_enb;  // ufix1
  wire Out1_lastAddr;  // ufix1
  wire [18:0] Out1_addr_delay_1;  // ufix19
  reg signed [31:0] fp_Out1_expected;  // sfix32
  reg signed [15:0] Out1_expected;  // sfix16_En22
  reg signed [31:0] status_Out1_expected;  // sfix32
  reg signed [15:0] Out1_ref_hold;  // sfix16_En22
  wire signed [15:0] Out1_refTmp;  // sfix16_En22
  wire signed [15:0] Out1_ref;  // sfix16_En22
  reg  Out1_testFailure;  // ufix1
  wire testFailure;  // ufix1


  assign Out1_done_enb = Out1_done & ce_out;



  assign Out1_active = Out1_addr != 19'b1101011101010101000;



  assign Data_Type_Conversion_out1_active = Data_Type_Conversion_out1_addr != 19'b1101011101010101000;



  assign Data_Type_Conversion_out1_enb = Data_Type_Conversion_out1_active & (tb_enb_delay & tb_enb_delay);



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 441000
  always @(posedge clk)
    begin : DataTypeConversion_process
      if (reset == 1'b1) begin
        Data_Type_Conversion_out1_addr <= 19'b0000000000000000000;
      end
      else begin
        if (Data_Type_Conversion_out1_enb) begin
          if (Data_Type_Conversion_out1_addr >= 19'b1101011101010101000) begin
            Data_Type_Conversion_out1_addr <= 19'b0000000000000000000;
          end
          else begin
            Data_Type_Conversion_out1_addr <= Data_Type_Conversion_out1_addr + 19'b0000000000000000001;
          end
        end
      end
    end



  assign #1 Data_Type_Conversion_out1_addr_delay_1 = Data_Type_Conversion_out1_addr;

  // Data source for In1
  initial
    begin : In1_fileread
      fp_In1 = $fopen("In1.dat", "r");
      status_In1 = $rewind(fp_In1);
    end

  always @(Data_Type_Conversion_out1_addr_delay_1, tb_enb_delay, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_In1 <= 16'bx;
      end
      else if (tb_enb_delay == 1) begin
        status_In1 = $fscanf(fp_In1, "%h", rawData_In1);
      end
    end

  // holdData reg for Data_Type_Conversion_out1
  always @(posedge clk)
    begin : stimuli_Data_Type_Conversion_out1
      if (reset) begin
        holdData_In1 <= 16'bx;
      end
      else begin
        holdData_In1 <= rawData_In1;
      end
    end

  always @(rawData_In1 or tb_enb_delay)
    begin : stimuli_Data_Type_Conversion_out1_1
      if (tb_enb_delay == 1'b0) begin
        In1_offset <= holdData_In1;
      end
      else begin
        In1_offset <= rawData_In1;
      end
    end

  assign #2 In1 = In1_offset;

  assign snkDonen =  ~ check1_done;



  assign resetn =  ~ reset;



  assign tb_enb = resetn & snkDonen;



  // Delay inside enable generation: register depth 1
  always @(posedge clk)
    begin : u_enable_delay
      if (reset) begin
        tb_enb_delay <= 0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end

  assign notDone = tb_enb_delay & snkDonen;



  assign #2 clk_enable = notDone;

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (check1_done == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  DWT_Sym2_Level3 u_DWT_Sym2_Level3 (.clk(clk),
                                     .reset(reset),
                                     .clk_enable(clk_enable),
                                     .In1(In1),  // ufix16_En23
                                     .ce_out(ce_out),
                                     .Out1(Out1)  // sfix16_En22
                                     );

  assign Out1_enb = ce_out & Out1_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 441000
  always @(posedge clk)
    begin : c_2_process
      if (reset == 1'b1) begin
        Out1_addr <= 19'b0000000000000000000;
      end
      else begin
        if (Out1_enb) begin
          if (Out1_addr >= 19'b1101011101010101000) begin
            Out1_addr <= 19'b0000000000000000000;
          end
          else begin
            Out1_addr <= Out1_addr + 19'b0000000000000000001;
          end
        end
      end
    end



  assign Out1_lastAddr = Out1_addr >= 19'b1101011101010101000;



  assign Out1_done = Out1_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (Out1_done_enb) begin
          check1_done <= Out1_done;
        end
      end
    end

  assign #1 Out1_addr_delay_1 = Out1_addr;

  // Data source for Out1_expected
  initial
    begin : Out1_expected_fileread
      fp_Out1_expected = $fopen("Out1_expected.dat", "r");
      status_Out1_expected = $rewind(fp_Out1_expected);
    end

  always @(Out1_addr_delay_1,  tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        Out1_expected <= 16'bx;
      end
      else  begin
        status_Out1_expected = $fscanf(fp_Out1_expected, "%h", Out1_expected);
      end
    end

  // Bypass register to hold Out1_ref
  always @(posedge clk)
    begin : DataHold_Out1_ref
      if (reset) begin
        Out1_ref_hold <= 0;
      end
      else begin
        if (ce_out) begin
          Out1_ref_hold <= Out1_expected;
        end
      end
    end

  assign Out1_refTmp = Out1_expected;

  assign Out1_ref = (ce_out == 1'b0 ? Out1_ref_hold :
              Out1_refTmp);



  always @(posedge clk)
    begin : Out1_checker
      if (reset == 1'b1) begin
        Out1_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && Out1 !== Out1_ref) begin
          Out1_testFailure <= 1'b1;
          $display("ERROR in Out1 at time %t : Expected '%h' Actual '%h'", $time, Out1_ref, Out1);
        end
      end
    end

  assign testFailure = Out1_testFailure;

  always @(posedge clk)
    begin : completed_msg
      if (check1_done == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // DWT_Sym2_Level3_tb

