// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\sym5_2_Level\LoD_Odd.v
// Created: 2024-04-18 15:07:23
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LoD_Odd
// Source Path: sym5_2_Level/DWT_sym5_2_Level/1st_Level_Decomp/LoD_Odd
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LoD_Odd
          (clk,
           reset,
           enb,
           In_HiD_e,
           Out_HiD_e);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] In_HiD_e;  // ufix16_En24
  output  [15:0] Out_HiD_e;  // ufix16_En24


  wire [15:0] LoD_1_out1;  // ufix16_En21
  reg [15:0] LoD_1_out1_1;  // ufix16_En21
  reg [15:0] In_HiD_e_1;  // ufix16_En24
  wire [31:0] Multiply_mul_temp;  // ufix32_En45
  wire [15:0] Multiply_out1;  // ufix16_En29
  reg [15:0] Multiply_out1_1;  // ufix16_En29
  wire [15:0] LoD_3_out1;  // ufix16_En18
  reg [15:0] LoD_3_out1_1;  // ufix16_En18
  reg [15:0] Rate_Transition_out1;  // ufix16_En24
  wire [31:0] Multiply1_mul_temp;  // ufix32_En42
  wire [15:0] Multiply1_out1;  // ufix16_En26
  reg [15:0] Multiply1_out1_1;  // ufix16_En26
  wire [15:0] LoD_5_out1;  // ufix16_En16
  reg [15:0] LoD_5_out1_1;  // ufix16_En16
  reg [15:0] Rate_Transition1_out1;  // ufix16_En24
  wire [31:0] Multiply2_mul_temp;  // ufix32_En40
  wire [15:0] Multiply2_out1;  // ufix16_En24
  reg [15:0] Multiply2_out1_1;  // ufix16_En24
  wire signed [15:0] LoD_7_out1;  // sfix16_En17
  reg signed [15:0] LoD_7_out1_1;  // sfix16_En17
  reg [15:0] Rate_Transition4_out1;  // ufix16_En24
  wire signed [16:0] Multiply3_cast;  // sfix17_En24
  wire signed [32:0] Multiply3_mul_temp;  // sfix33_En41
  wire signed [31:0] Multiply3_cast_1;  // sfix32_En41
  wire signed [15:0] Multiply3_out1;  // sfix16_En15
  reg signed [15:0] Multiply3_out1_1;  // sfix16_En15
  wire [15:0] LoD_9_out1;  // ufix16_En21
  reg [15:0] LoD_9_out1_1;  // ufix16_En21
  reg [15:0] Rate_Transition2_out1;  // ufix16_En24
  wire [31:0] Multiply4_mul_temp;  // ufix32_En45
  wire [15:0] Multiply4_out1;  // ufix16_En30
  reg [15:0] delayMatch_reg [0:1];  // ufix16 [2]
  wire [15:0] delayMatch_reg_next [0:1];  // ufix16_En30 [2]
  wire [15:0] Multiply4_out1_1;  // ufix16_En30
  wire signed [15:0] Add2_add_cast;  // sfix16_En25
  wire signed [15:0] Add2_add_cast_1;  // sfix16_En25
  wire signed [15:0] Add2_add_temp;  // sfix16_En25
  wire signed [15:0] Add2_out1;  // sfix16_En15
  reg signed [15:0] Delay9_out1;  // sfix16_En15
  wire signed [15:0] Add4_add_cast;  // sfix16_En23
  wire signed [15:0] Add4_add_cast_1;  // sfix16_En23
  wire signed [15:0] Add4_add_temp;  // sfix16_En23
  wire [15:0] Add4_out1;  // ufix16_En25
  reg [15:0] Delay2_out1;  // ufix16_En25
  wire [15:0] Add1_add_cast;  // ufix16_En24
  wire [15:0] Add1_add_cast_1;  // ufix16_En24
  wire [15:0] Add1_out1;  // ufix16_En24
  reg [15:0] Delay3_out1;  // ufix16_En24
  wire [15:0] Add_add_cast;  // ufix16_En24
  wire [15:0] Add_out1;  // ufix16_En24


  assign LoD_1_out1 = 16'b1111000111010011;


  always @(posedge clk)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        LoD_1_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_1_out1_1 <= LoD_1_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_process
      if (reset == 1'b1) begin
        In_HiD_e_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          In_HiD_e_1 <= In_HiD_e;
        end
      end
    end


  assign Multiply_mul_temp = LoD_1_out1_1 * In_HiD_e_1;
  assign Multiply_out1 = Multiply_mul_temp[31:16];


  always @(posedge clk)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Multiply_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply_out1_1 <= Multiply_out1;
        end
      end
    end



  assign LoD_3_out1 = 16'b1100110000101111;


  always @(posedge clk)
    begin : HwModeRegister2_process
      if (reset == 1'b1) begin
        LoD_3_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_3_out1_1 <= LoD_3_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        Rate_Transition_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition_out1 <= In_HiD_e_1;
        end
      end
    end


  assign Multiply1_mul_temp = LoD_3_out1_1 * Rate_Transition_out1;
  assign Multiply1_out1 = Multiply1_mul_temp[31:16];


  always @(posedge clk)
    begin : PipelineRegister1_process
      if (reset == 1'b1) begin
        Multiply1_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply1_out1_1 <= Multiply1_out1;
        end
      end
    end



  assign LoD_5_out1 = 16'b1010001001001100;


  always @(posedge clk)
    begin : HwModeRegister4_process
      if (reset == 1'b1) begin
        LoD_5_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_5_out1_1 <= LoD_5_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_2_process
      if (reset == 1'b1) begin
        Rate_Transition1_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition1_out1 <= Rate_Transition_out1;
        end
      end
    end


  assign Multiply2_mul_temp = LoD_5_out1_1 * Rate_Transition1_out1;
  assign Multiply2_out1 = Multiply2_mul_temp[31:16];


  always @(posedge clk)
    begin : PipelineRegister2_process
      if (reset == 1'b1) begin
        Multiply2_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply2_out1_1 <= Multiply2_out1;
        end
      end
    end



  assign LoD_7_out1 = 16'sb1010011000111011;


  always @(posedge clk)
    begin : HwModeRegister6_process
      if (reset == 1'b1) begin
        LoD_7_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_7_out1_1 <= LoD_7_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_3_process
      if (reset == 1'b1) begin
        Rate_Transition4_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition4_out1 <= Rate_Transition1_out1;
        end
      end
    end


  assign Multiply3_cast = {1'b0, Rate_Transition4_out1};
  assign Multiply3_mul_temp = LoD_7_out1_1 * Multiply3_cast;
  assign Multiply3_cast_1 = Multiply3_mul_temp[31:0];
  assign Multiply3_out1 = {{10{Multiply3_cast_1[31]}}, Multiply3_cast_1[31:26]};


  always @(posedge clk)
    begin : PipelineRegister3_process
      if (reset == 1'b1) begin
        Multiply3_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply3_out1_1 <= Multiply3_out1;
        end
      end
    end



  assign LoD_9_out1 = 16'b1010000000010000;


  always @(posedge clk)
    begin : HwModeRegister8_process
      if (reset == 1'b1) begin
        LoD_9_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_9_out1_1 <= LoD_9_out1;
        end
      end
    end



  always @(posedge clk)
    begin : HwModeRegister9_process
      if (reset == 1'b1) begin
        Rate_Transition2_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition2_out1 <= Rate_Transition4_out1;
        end
      end
    end



  assign Multiply4_mul_temp = LoD_9_out1_1 * Rate_Transition2_out1;
  assign Multiply4_out1 = Multiply4_mul_temp[30:15];


  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 16'b0000000000000000;
        delayMatch_reg[1] <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
        end
      end
    end

  assign Multiply4_out1_1 = delayMatch_reg[1];
  assign delayMatch_reg_next[0] = Multiply4_out1;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];



  assign Add2_add_cast = {Multiply3_out1_1[5:0], 10'b0000000000};
  assign Add2_add_cast_1 = {5'b0, Multiply4_out1_1[15:5]};
  assign Add2_add_temp = Add2_add_cast + Add2_add_cast_1;
  assign Add2_out1 = {{10{Add2_add_temp[15]}}, Add2_add_temp[15:10]};


  always @(posedge clk)
    begin : Delay9_process
      if (reset == 1'b1) begin
        Delay9_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay9_out1 <= Add2_out1;
        end
      end
    end


  assign Add4_add_cast = {1'b0, Multiply2_out1_1[15:1]};
  assign Add4_add_cast_1 = {Delay9_out1[7:0], 8'b00000000};
  assign Add4_add_temp = Add4_add_cast + Add4_add_cast_1;
  assign Add4_out1 = {Add4_add_temp[13:0], 2'b00};


  always @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Add4_out1;
        end
      end
    end


  assign Add1_add_cast = {2'b0, Multiply1_out1_1[15:2]};
  assign Add1_add_cast_1 = {1'b0, Delay2_out1[15:1]};
  assign Add1_out1 = Add1_add_cast + Add1_add_cast_1;


  always @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Add1_out1;
        end
      end
    end


  assign Add_add_cast = {5'b0, Multiply_out1_1[15:5]};
  assign Add_out1 = Add_add_cast + Delay3_out1;


  assign Out_HiD_e = Add_out1;

endmodule  // LoD_Odd

