open_system('gm_final_heart_sym4_2_Level_fixed');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1', 'user2');
annotate_port('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1', 0, 1, 'cp : 14.634 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/HiR_Even', 'user2');
annotate_port('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/HiR_Even', 0, 1, 'cp : 4.759 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/Add3', 'user2');
annotate_port('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/Add3', 0, 1, 'cp : 9.518 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/Add5', 'user2');
annotate_port('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/Add5', 0, 1, 'cp : 14.277 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/HwModeRegister1', 'user1');
annotate_port('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/HwModeRegister1', 1, 1, 'cp : 14.634 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/HiR_Even/Add3', 'user2');
annotate_port('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/HiR_Even/Add3', 0, 1, 'cp : 4.759 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/HiR_Even/PipelineRegister3', 'user1');
annotate_port('gm_final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Recon1/HiR_Even/PipelineRegister3', 0, 1, 'cp : 0 ns');
