open_system('gm_final_heart_sym2_level3_fixed');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon', 'user2');
annotate_port('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1', 'user2');
annotate_port('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1', 1, 2, 'cp : 14.555 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon/Delay1', 'user1');
annotate_port('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon/Delay1', 0, 1, 'cp : 0.298 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/LoR_Even', 'user2');
annotate_port('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/LoR_Even', 0, 1, 'cp : 6.831 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/Delay1', 'user1');
annotate_port('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/Delay1', 1, 1, 'cp : 14.555 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/Gain', 'user2');
annotate_port('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/Gain', 0, 1, 'cp : 14.525 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/RT2', 'user2');
annotate_port('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/RT2', 0, 1, 'cp : 14.525 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/Add', 'user2');
annotate_port('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/Add', 0, 1, 'cp : 7.835 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/Add2', 'user2');
annotate_port('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/Add2', 0, 1, 'cp : 8.958 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/LoR_Even/Add', 'user2');
annotate_port('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/LoR_Even/Add', 0, 1, 'cp : 6.831 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/LoR_Even/Multiply', 'user2');
annotate_port('gm_final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon1/LoR_Even/Multiply', 0, 1, 'cp : 5.708 ns');
