// -------------------------------------------------------------
// 
// File Name: hdlsrc\final_heart_sym2_level3_fixed\HiD_Even.v
// Created: 2024-04-17 00:25:34
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HiD_Even
// Source Path: final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Decomp/HiD_Even
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HiD_Even
          (clk,
           reset,
           enb,
           In_HiD_e,
           Out_HiD_e);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] In_HiD_e;  // ufix16_En23
  output  signed [15:0] Out_HiD_e;  // sfix16_En15


  wire signed [15:0] HiD_0_out1;  // sfix16_En16
  wire signed [16:0] Multiply_cast;  // sfix17_En23
  wire signed [32:0] Multiply_mul_temp;  // sfix33_En39
  wire signed [31:0] Multiply_cast_1;  // sfix32_En39
  wire signed [15:0] Multiply_out1;  // sfix16_En15
  wire signed [15:0] HiD_2_out1;  // sfix16_En17
  reg [15:0] Delay_out1;  // ufix16_En23
  wire signed [16:0] Multiply1_cast;  // sfix17_En23
  wire signed [32:0] Multiply1_mul_temp;  // sfix33_En40
  wire signed [31:0] Multiply1_cast_1;  // sfix32_En40
  wire signed [15:0] Multiply1_out1;  // sfix16_En15
  reg signed [15:0] Delay3_out1;  // sfix16_En15
  wire signed [15:0] Add_out1;  // sfix16_En15


  assign HiD_0_out1 = 16'sb1000010001011101;


  assign Multiply_cast = {1'b0, In_HiD_e};
  assign Multiply_mul_temp = HiD_0_out1 * Multiply_cast;
  assign Multiply_cast_1 = Multiply_mul_temp[31:0];
  assign Multiply_out1 = {{8{Multiply_cast_1[31]}}, Multiply_cast_1[31:24]};


  assign HiD_2_out1 = 16'sb1000110100111101;


  always @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= In_HiD_e;
        end
      end
    end


  assign Multiply1_cast = {1'b0, Delay_out1};
  assign Multiply1_mul_temp = HiD_2_out1 * Multiply1_cast;
  assign Multiply1_cast_1 = Multiply1_mul_temp[31:0];
  assign Multiply1_out1 = {{9{Multiply1_cast_1[31]}}, Multiply1_cast_1[31:25]};


  always @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Multiply1_out1;
        end
      end
    end


  assign Add_out1 = Multiply_out1 + Delay3_out1;


  assign Out_HiD_e = Add_out1;

endmodule  // HiD_Even

