// -------------------------------------------------------------
// 
// File Name: hdlsrc\final_heart_sym2_level3_fixed\HiD_Even_block.v
// Created: 2024-04-17 00:25:34
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HiD_Even_block
// Source Path: final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Decomp1/HiD_Even
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HiD_Even_block
          (clk,
           reset,
           enb,
           In_HiD_e,
           Out_HiD_e);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In_HiD_e;  // sfix16_En22
  output  signed [15:0] Out_HiD_e;  // sfix16_En15


  wire signed [15:0] HiD_0_out1;  // sfix16_En16
  wire signed [31:0] Multiply_mul_temp;  // sfix32_En38
  wire signed [15:0] Multiply_out1;  // sfix16_En15
  wire signed [15:0] HiD_2_out1;  // sfix16_En17
  reg signed [15:0] Delay_out1;  // sfix16_En22
  wire signed [31:0] Multiply1_mul_temp;  // sfix32_En39
  wire signed [15:0] Multiply1_out1;  // sfix16_En15
  reg signed [15:0] Delay3_out1;  // sfix16_En15
  wire signed [15:0] Add_out1;  // sfix16_En15


  assign HiD_0_out1 = 16'sb1000010001011101;


  assign Multiply_mul_temp = HiD_0_out1 * In_HiD_e;
  assign Multiply_out1 = {{7{Multiply_mul_temp[31]}}, Multiply_mul_temp[31:23]};


  assign HiD_2_out1 = 16'sb1000110100111101;


  always @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= In_HiD_e;
        end
      end
    end


  assign Multiply1_mul_temp = HiD_2_out1 * Delay_out1;
  assign Multiply1_out1 = {{8{Multiply1_mul_temp[31]}}, Multiply1_mul_temp[31:24]};


  always @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Multiply1_out1;
        end
      end
    end


  assign Add_out1 = Multiply_out1 + Delay3_out1;


  assign Out_HiD_e = Add_out1;

endmodule  // HiD_Even_block

