// -------------------------------------------------------------
// 
// File Name: hdlsrc\final_heart_sym2_level3_fixed\HiR_Even_block1.v
// Created: 2024-04-17 00:25:34
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HiR_Even_block1
// Source Path: final_heart_sym2_level3_fixed/DWT_sym2_3_Level/1st_Level_Recon2/HiR_Even
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HiR_Even_block1
          (clk,
           reset,
           enb,
           In_HiR_e,
           Out_HiR_e);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In_HiR_e;  // sfix16_En28
  output  signed [15:0] Out_HiR_e;  // sfix16_En28


  wire signed [15:0] Constant12_out1;  // sfix16_En17
  wire signed [31:0] Multiply_mul_temp;  // sfix32_En45
  wire signed [15:0] Multiply_out1;  // sfix16_En30
  wire [15:0] Constant14_out1;  // ufix16_En16
  reg signed [15:0] Delay_out1;  // sfix16_En28
  wire signed [16:0] Multiply1_cast;  // sfix17_En16
  wire signed [32:0] Multiply1_mul_temp;  // sfix33_En44
  wire signed [31:0] Multiply1_cast_1;  // sfix32_En44
  wire signed [15:0] Multiply1_out1;  // sfix16_En28
  reg signed [15:0] Delay3_out1;  // sfix16_En28
  wire signed [15:0] Add_add_cast;  // sfix16_En28
  wire signed [15:0] Add_out1;  // sfix16_En28


  assign Constant12_out1 = 16'sb1011110110111110;


  assign Multiply_mul_temp = Constant12_out1 * In_HiR_e;
  assign Multiply_out1 = Multiply_mul_temp[30:15];


  assign Constant14_out1 = 16'b1101011000100110;


  always @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= In_HiR_e;
        end
      end
    end


  assign Multiply1_cast = {1'b0, Constant14_out1};
  assign Multiply1_mul_temp = Multiply1_cast * Delay_out1;
  assign Multiply1_cast_1 = Multiply1_mul_temp[31:0];
  assign Multiply1_out1 = Multiply1_cast_1[31:16];


  always @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Multiply1_out1;
        end
      end
    end


  assign Add_add_cast = {{2{Multiply_out1[15]}}, Multiply_out1[15:2]};
  assign Add_out1 = Add_add_cast + Delay3_out1;


  assign Out_HiR_e = Add_out1;

endmodule  // HiR_Even_block1

