// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\db5_2level_final_hdl\HiR_Even_block.v
// Created: 2024-04-17 05:55:27
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HiR_Even_block
// Source Path: db5_2level_final_hdl/DWT_db5_2level/1st_Level_Recon1/HiR_Even
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HiR_Even_block
          (clk,
           reset,
           enb,
           In_HiR_e,
           Out_HiR_e);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In_HiR_e;  // sfix16_En26
  output  signed [15:0] Out_HiR_e;  // sfix16_En26


  wire [15:0] HiR_0_out1;  // ufix16_En24
  reg [15:0] HiR_0_out1_1;  // ufix16_En24
  reg signed [15:0] In_HiR_e_1;  // sfix16_En26
  wire signed [16:0] Multiply_cast;  // sfix17_En24
  wire signed [32:0] Multiply_mul_temp;  // sfix33_En50
  wire signed [31:0] Multiply_cast_1;  // sfix32_En50
  wire signed [15:0] Multiply_out1;  // sfix16_En34
  reg signed [15:0] Multiply_out1_1;  // sfix16_En34
  wire signed [15:0] HiR_2_out1;  // sfix16_En22
  reg signed [15:0] HiR_2_out1_1;  // sfix16_En22
  reg signed [15:0] Rate_Transition_out1;  // sfix16_En26
  wire signed [31:0] Multiply1_mul_temp;  // sfix32_En48
  wire signed [15:0] Multiply1_out1;  // sfix16_En33
  reg signed [15:0] Multiply1_out1_1;  // sfix16_En33
  wire signed [15:0] HiR_4_out1;  // sfix16_En19
  reg signed [15:0] HiR_4_out1_1;  // sfix16_En19
  reg signed [15:0] Rate_Transition1_out1;  // sfix16_En26
  wire signed [31:0] Multiply2_mul_temp;  // sfix32_En45
  wire signed [15:0] Multiply2_out1;  // sfix16_En31
  reg signed [15:0] Multiply2_out1_1;  // sfix16_En31
  wire [15:0] HiR_6_out1;  // ufix16_En18
  reg [15:0] HiR_6_out1_1;  // ufix16_En18
  reg signed [15:0] Rate_Transition2_out1;  // sfix16_En26
  wire signed [16:0] Multiply3_cast;  // sfix17_En18
  wire signed [32:0] Multiply3_mul_temp;  // sfix33_En44
  wire signed [31:0] Multiply3_cast_1;  // sfix32_En44
  wire signed [15:0] Multiply3_out1;  // sfix16_En28
  reg signed [15:0] Multiply3_out1_1;  // sfix16_En28
  wire [15:0] HiR_8_out1;  // ufix16_En16
  reg [15:0] HiR_8_out1_1;  // ufix16_En16
  reg signed [15:0] Rate_Transition3_out1;  // sfix16_En26
  wire signed [16:0] Multiply4_cast;  // sfix17_En16
  wire signed [32:0] Multiply4_mul_temp;  // sfix33_En42
  wire signed [31:0] Multiply4_cast_1;  // sfix32_En42
  wire signed [15:0] Multiply4_out1;  // sfix16_En26
  reg signed [15:0] delayMatch_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch_reg_next [0:1];  // sfix16_En26 [2]
  wire signed [15:0] Multiply4_out1_1;  // sfix16_En26
  wire signed [15:0] Add3_add_cast;  // sfix16_En26
  wire signed [15:0] Add3_out1;  // sfix16_En26
  reg signed [15:0] Delay5_out1;  // sfix16_En26
  wire signed [15:0] Add2_add_cast;  // sfix16_En26
  wire signed [15:0] Add2_out1;  // sfix16_En26
  reg signed [15:0] Delay2_out1;  // sfix16_En26
  wire signed [15:0] Add1_add_cast;  // sfix16_En26
  wire signed [15:0] Add1_out1;  // sfix16_En26
  reg signed [15:0] Delay3_out1;  // sfix16_En26
  wire signed [15:0] Add_add_cast;  // sfix16_En26
  wire signed [15:0] Add_out1;  // sfix16_En26


  assign HiR_0_out1 = 16'b1101101010011100;


  always @(posedge clk)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        HiR_0_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HiR_0_out1_1 <= HiR_0_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_process
      if (reset == 1'b1) begin
        In_HiR_e_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          In_HiR_e_1 <= In_HiR_e;
        end
      end
    end


  assign Multiply_cast = {1'b0, HiR_0_out1_1};
  assign Multiply_mul_temp = Multiply_cast * In_HiR_e_1;
  assign Multiply_cast_1 = Multiply_mul_temp[31:0];
  assign Multiply_out1 = Multiply_cast_1[31:16];


  always @(posedge clk)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Multiply_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply_out1_1 <= Multiply_out1;
        end
      end
    end



  assign HiR_2_out1 = 16'sb1001100110111101;


  always @(posedge clk)
    begin : HwModeRegister2_process
      if (reset == 1'b1) begin
        HiR_2_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          HiR_2_out1_1 <= HiR_2_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        Rate_Transition_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition_out1 <= In_HiR_e_1;
        end
      end
    end


  assign Multiply1_mul_temp = HiR_2_out1_1 * Rate_Transition_out1;
  assign Multiply1_out1 = Multiply1_mul_temp[30:15];


  always @(posedge clk)
    begin : PipelineRegister1_process
      if (reset == 1'b1) begin
        Multiply1_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply1_out1_1 <= Multiply1_out1;
        end
      end
    end



  assign HiR_4_out1 = 16'sb1011110111110110;


  always @(posedge clk)
    begin : HwModeRegister4_process
      if (reset == 1'b1) begin
        HiR_4_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          HiR_4_out1_1 <= HiR_4_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_2_process
      if (reset == 1'b1) begin
        Rate_Transition1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition1_out1 <= Rate_Transition_out1;
        end
      end
    end


  assign Multiply2_mul_temp = HiR_4_out1_1 * Rate_Transition1_out1;
  assign Multiply2_out1 = Multiply2_mul_temp[29:14];


  always @(posedge clk)
    begin : PipelineRegister2_process
      if (reset == 1'b1) begin
        Multiply2_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply2_out1_1 <= Multiply2_out1;
        end
      end
    end



  assign HiR_6_out1 = 16'b1000110111000000;


  always @(posedge clk)
    begin : HwModeRegister6_process
      if (reset == 1'b1) begin
        HiR_6_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HiR_6_out1_1 <= HiR_6_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_3_process
      if (reset == 1'b1) begin
        Rate_Transition2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition2_out1 <= Rate_Transition1_out1;
        end
      end
    end


  assign Multiply3_cast = {1'b0, HiR_6_out1_1};
  assign Multiply3_mul_temp = Multiply3_cast * Rate_Transition2_out1;
  assign Multiply3_cast_1 = Multiply3_mul_temp[31:0];
  assign Multiply3_out1 = Multiply3_cast_1[31:16];


  always @(posedge clk)
    begin : PipelineRegister3_process
      if (reset == 1'b1) begin
        Multiply3_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply3_out1_1 <= Multiply3_out1;
        end
      end
    end



  assign HiR_8_out1 = 16'b1001101010010101;


  always @(posedge clk)
    begin : HwModeRegister8_process
      if (reset == 1'b1) begin
        HiR_8_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HiR_8_out1_1 <= HiR_8_out1;
        end
      end
    end



  always @(posedge clk)
    begin : HwModeRegister9_process
      if (reset == 1'b1) begin
        Rate_Transition3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition3_out1 <= Rate_Transition2_out1;
        end
      end
    end



  assign Multiply4_cast = {1'b0, HiR_8_out1_1};
  assign Multiply4_mul_temp = Multiply4_cast * Rate_Transition3_out1;
  assign Multiply4_cast_1 = Multiply4_mul_temp[31:0];
  assign Multiply4_out1 = Multiply4_cast_1[31:16];


  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 16'sb0000000000000000;
        delayMatch_reg[1] <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
        end
      end
    end

  assign Multiply4_out1_1 = delayMatch_reg[1];
  assign delayMatch_reg_next[0] = Multiply4_out1;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];



  assign Add3_add_cast = {{2{Multiply3_out1_1[15]}}, Multiply3_out1_1[15:2]};
  assign Add3_out1 = Add3_add_cast + Multiply4_out1_1;


  always @(posedge clk)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay5_out1 <= Add3_out1;
        end
      end
    end


  assign Add2_add_cast = {{5{Multiply2_out1_1[15]}}, Multiply2_out1_1[15:5]};
  assign Add2_out1 = Add2_add_cast + Delay5_out1;


  always @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Add2_out1;
        end
      end
    end


  assign Add1_add_cast = {{7{Multiply1_out1_1[15]}}, Multiply1_out1_1[15:7]};
  assign Add1_out1 = Add1_add_cast + Delay2_out1;


  always @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Add1_out1;
        end
      end
    end


  assign Add_add_cast = {{8{Multiply_out1_1[15]}}, Multiply_out1_1[15:8]};
  assign Add_out1 = Add_add_cast + Delay3_out1;


  assign Out_HiR_e = Add_out1;

endmodule  // HiR_Even_block

