// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\final_heart_sym4_2_Level_fixed\LoD_Odd_block.v
// Created: 2024-04-15 21:31:10
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LoD_Odd_block
// Source Path: final_heart_sym4_2_Level_fixed/DWT_sym4_2_Level/1st_Level_Decomp1/LoD_Odd
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LoD_Odd_block
          (clk,
           reset,
           enb,
           In_LoD_o,
           Out_LoD_o);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In_LoD_o;  // sfix16_En23
  output  signed [15:0] Out_LoD_o;  // sfix16_En23


  wire signed [15:0] LoD_1_out1;  // sfix16_En20
  reg signed [15:0] LoD_1_out1_1;  // sfix16_En20
  reg signed [15:0] In_LoD_o_1;  // sfix16_En23
  wire signed [31:0] Multiply4_mul_temp;  // sfix32_En43
  wire signed [15:0] Multiply4_out1;  // sfix16_En15
  reg signed [15:0] Multiply4_out1_1;  // sfix16_En15
  wire [15:0] LoD_3_out1;  // ufix16_En16
  reg [15:0] LoD_3_out1_1;  // ufix16_En16
  reg signed [15:0] Rate_Transition_out1;  // sfix16_En23
  wire signed [16:0] Multiply_cast;  // sfix17_En16
  wire signed [32:0] Multiply_mul_temp;  // sfix33_En39
  wire signed [31:0] Multiply_cast_1;  // sfix32_En39
  wire [15:0] Multiply_out1;  // ufix16_En24
  reg [15:0] Multiply_out1_1;  // ufix16_En24
  wire signed [15:0] LoD_5_out1;  // sfix16_En18
  reg signed [15:0] LoD_5_out1_1;  // sfix16_En18
  reg signed [15:0] Rate_Transition1_out1;  // sfix16_En23
  wire signed [31:0] Multiply1_mul_temp;  // sfix32_En41
  wire signed [15:0] Multiply1_out1;  // sfix16_En15
  reg signed [15:0] Multiply1_out1_1;  // sfix16_En15
  wire [15:0] LoD_7_out1;  // ufix16_En20
  reg [15:0] LoD_7_out1_1;  // ufix16_En20
  reg signed [15:0] Rate_Transition2_out1;  // sfix16_En23
  wire signed [16:0] Multiply2_cast;  // sfix17_En20
  wire signed [32:0] Multiply2_mul_temp;  // sfix33_En43
  wire signed [31:0] Multiply2_cast_1;  // sfix32_En43
  wire [15:0] Multiply2_out1;  // ufix16_En29
  reg [15:0] delayMatch_reg [0:1];  // ufix16 [2]
  wire [15:0] delayMatch_reg_next [0:1];  // ufix16_En29 [2]
  wire [15:0] Multiply2_out1_1;  // ufix16_En29
  wire signed [15:0] Add1_add_cast;  // sfix16_En26
  wire signed [15:0] Add1_add_cast_1;  // sfix16_En26
  wire signed [15:0] Add1_out1;  // sfix16_En26
  reg signed [15:0] Delay3_out1;  // sfix16_En26
  wire signed [15:0] Add_add_cast;  // sfix16_En23
  wire signed [15:0] Add_add_cast_1;  // sfix16_En23
  wire signed [15:0] Add_out1;  // sfix16_En23
  reg signed [15:0] Delay2_out1;  // sfix16_En23
  wire signed [15:0] Add3_add_cast;  // sfix16_En23
  wire signed [15:0] Add3_out1;  // sfix16_En23


  assign LoD_1_out1 = 16'sb1000011010011101;


  always @(posedge clk)
    begin : HwModeRegister6_process
      if (reset == 1'b1) begin
        LoD_1_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_1_out1_1 <= LoD_1_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_process
      if (reset == 1'b1) begin
        In_LoD_o_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          In_LoD_o_1 <= In_LoD_o;
        end
      end
    end


  assign Multiply4_mul_temp = LoD_1_out1_1 * In_LoD_o_1;
  assign Multiply4_out1 = {{12{Multiply4_mul_temp[31]}}, Multiply4_mul_temp[31:28]};


  always @(posedge clk)
    begin : PipelineRegister3_process
      if (reset == 1'b1) begin
        Multiply4_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply4_out1_1 <= Multiply4_out1;
        end
      end
    end



  assign LoD_3_out1 = 16'b1100110111000010;


  always @(posedge clk)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        LoD_3_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_3_out1_1 <= LoD_3_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        Rate_Transition_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition_out1 <= In_LoD_o_1;
        end
      end
    end


  assign Multiply_cast = {1'b0, LoD_3_out1_1};
  assign Multiply_mul_temp = Multiply_cast * Rate_Transition_out1;
  assign Multiply_cast_1 = Multiply_mul_temp[31:0];
  assign Multiply_out1 = Multiply_cast_1[30:15];


  always @(posedge clk)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Multiply_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply_out1_1 <= Multiply_out1;
        end
      end
    end



  assign LoD_5_out1 = 16'sb1001101001100110;


  always @(posedge clk)
    begin : HwModeRegister2_process
      if (reset == 1'b1) begin
        LoD_5_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_5_out1_1 <= LoD_5_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_2_process
      if (reset == 1'b1) begin
        Rate_Transition1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition1_out1 <= Rate_Transition_out1;
        end
      end
    end


  assign Multiply1_mul_temp = LoD_5_out1_1 * Rate_Transition1_out1;
  assign Multiply1_out1 = {{10{Multiply1_mul_temp[31]}}, Multiply1_mul_temp[31:26]};


  always @(posedge clk)
    begin : PipelineRegister1_process
      if (reset == 1'b1) begin
        Multiply1_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply1_out1_1 <= Multiply1_out1;
        end
      end
    end



  assign LoD_7_out1 = 16'b1000001111111100;


  always @(posedge clk)
    begin : HwModeRegister4_process
      if (reset == 1'b1) begin
        LoD_7_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          LoD_7_out1_1 <= LoD_7_out1;
        end
      end
    end



  always @(posedge clk)
    begin : HwModeRegister5_process
      if (reset == 1'b1) begin
        Rate_Transition2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition2_out1 <= Rate_Transition1_out1;
        end
      end
    end



  assign Multiply2_cast = {1'b0, LoD_7_out1_1};
  assign Multiply2_mul_temp = Multiply2_cast * Rate_Transition2_out1;
  assign Multiply2_cast_1 = Multiply2_mul_temp[31:0];
  assign Multiply2_out1 = Multiply2_cast_1[29:14];


  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 16'b0000000000000000;
        delayMatch_reg[1] <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
        end
      end
    end

  assign Multiply2_out1_1 = delayMatch_reg[1];
  assign delayMatch_reg_next[0] = Multiply2_out1;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];



  assign Add1_add_cast = {Multiply1_out1_1[4:0], 11'b00000000000};
  assign Add1_add_cast_1 = {3'b0, Multiply2_out1_1[15:3]};
  assign Add1_out1 = Add1_add_cast + Add1_add_cast_1;


  always @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Add1_out1;
        end
      end
    end


  assign Add_add_cast = {1'b0, Multiply_out1_1[15:1]};
  assign Add_add_cast_1 = {{3{Delay3_out1[15]}}, Delay3_out1[15:3]};
  assign Add_out1 = Add_add_cast + Add_add_cast_1;


  always @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Add_out1;
        end
      end
    end


  assign Add3_add_cast = {Multiply4_out1_1[7:0], 8'b00000000};
  assign Add3_out1 = Add3_add_cast + Delay2_out1;


  assign Out_LoD_o = Add3_out1;

endmodule  // LoD_Odd_block

