// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\db6_2level_final_hdl\DWT_db6_2level_tc.v
// Created: 2024-04-17 20:17:43
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DWT_db6_2level_tc
// Source Path: DWT_db6_2level_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb         : identical to clk_enable
// enb_1_1_1   : identical to clk_enable
// enb_1_30_0  : 30x slower than clk with last phase
// enb_1_30_1  : 30x slower than clk with phase 1
// enb_1_30_4  : 30x slower than clk with phase 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DWT_db6_2level_tc
          (clk,
           reset,
           clk_enable,
           enb,
           enb_1_1_1,
           enb_1_30_0,
           enb_1_30_1,
           enb_1_30_4);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb;
  output  enb_1_1_1;
  output  enb_1_30_0;
  output  enb_1_30_1;
  output  enb_1_30_4;


  reg [4:0] count30;  // ufix5
  wire phase_all;
  reg  phase_0;
  wire phase_0_tmp;
  reg  phase_1;
  wire phase_1_tmp;
  reg  phase_4;
  wire phase_4_tmp;


  always @ (posedge clk)
    begin: Counter30
      if (reset == 1'b1) begin
        count30 <= 5'b00001;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (count30 >= 5'b11101) begin
            count30 <= 5'b00000;
          end
          else begin
            count30 <= count30 + 5'b00001;
          end
        end
      end
    end // Counter30

  assign phase_all = clk_enable ? 1'b1 : 1'b0;

  always @ ( posedge clk)
    begin: temp_process1
      if (reset == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end // temp_process1

  assign  phase_0_tmp = (count30 == 5'b11101 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @ ( posedge clk)
    begin: temp_process2
      if (reset == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end // temp_process2

  assign  phase_1_tmp = (count30 == 5'b00000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @ ( posedge clk)
    begin: temp_process3
      if (reset == 1'b1) begin
        phase_4 <= 1'b0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_4 <= phase_4_tmp;
        end
      end
    end // temp_process3

  assign  phase_4_tmp = (count30 == 5'b00011 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign enb =  phase_all & clk_enable;

  assign enb_1_1_1 =  phase_all & clk_enable;

  assign enb_1_30_0 =  phase_0 & clk_enable;

  assign enb_1_30_1 =  phase_1 & clk_enable;

  assign enb_1_30_4 =  phase_4 & clk_enable;


endmodule  // DWT_db6_2level_tc

