// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\db6_2level_final_hdl\HiD_Odd_block.v
// Created: 2024-04-17 20:17:40
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HiD_Odd_block
// Source Path: db6_2level_final_hdl/DWT_db6_2level/1st_Level_Decomp6/HiD_Odd
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HiD_Odd_block
          (clk,
           reset,
           enb,
           In_HiD_o,
           Out_HiD_o);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In_HiD_o;  // sfix16_En24
  output  [15:0] Out_HiD_o;  // ufix16_En25


  wire [15:0] HiD_1_out1;  // ufix16_En17
  reg [15:0] HiD_1_out1_1;  // ufix16_En17
  reg signed [15:0] In_HiD_o_1;  // sfix16_En24
  wire signed [16:0] Multiply_cast;  // sfix17_En17
  wire signed [32:0] Multiply_mul_temp;  // sfix33_En41
  wire signed [31:0] Multiply_cast_1;  // sfix32_En41
  wire [15:0] Multiply_out1;  // ufix16_En26
  reg [15:0] Multiply_out1_1;  // ufix16_En26
  wire [15:0] HiD_3_out1;  // ufix16_En17
  reg [15:0] HiD_3_out1_1;  // ufix16_En17
  reg signed [15:0] Rate_Transition_out1;  // sfix16_En24
  wire signed [16:0] Multiply1_cast;  // sfix17_En17
  wire signed [32:0] Multiply1_mul_temp;  // sfix33_En41
  wire signed [31:0] Multiply1_cast_1;  // sfix32_En41
  wire [15:0] Multiply1_out1;  // ufix16_En26
  reg [15:0] Multiply1_out1_1;  // ufix16_En26
  wire signed [15:0] HiD_5_out1;  // sfix16_En17
  reg signed [15:0] HiD_5_out1_1;  // sfix16_En17
  reg signed [15:0] Rate_Transition1_out1;  // sfix16_En24
  wire signed [31:0] Multiply2_mul_temp;  // sfix32_En41
  wire signed [15:0] Multiply2_out1;  // sfix16_En15
  reg signed [15:0] Multiply2_out1_1;  // sfix16_En15
  wire [15:0] HiD_7_out1;  // ufix16_En21
  reg [15:0] HiD_7_out1_1;  // ufix16_En21
  reg signed [15:0] Rate_Transition2_out1;  // sfix16_En24
  wire signed [16:0] Multiply3_cast;  // sfix17_En21
  wire signed [32:0] Multiply3_mul_temp;  // sfix33_En45
  wire signed [31:0] Multiply3_cast_1;  // sfix32_En45
  wire [15:0] Multiply3_out1;  // ufix16_En30
  reg [15:0] Multiply3_out1_1;  // ufix16_En30
  wire [15:0] HiD_9_out1;  // ufix16_En26
  reg [15:0] HiD_9_out1_1;  // ufix16_En26
  reg signed [15:0] Rate_Transition3_out1;  // sfix16_En24
  wire signed [16:0] Multiply4_cast;  // sfix17_En26
  wire signed [32:0] Multiply4_mul_temp;  // sfix33_En50
  wire signed [31:0] Multiply4_cast_1;  // sfix32_En50
  wire [15:0] Multiply4_out1;  // ufix16_En35
  reg [15:0] Multiply4_out1_1;  // ufix16_En35
  wire signed [15:0] HiD_11_out1;  // sfix16_En24
  reg signed [15:0] HiD_11_out1_1;  // sfix16_En24
  reg signed [15:0] Rate_Transition4_out1;  // sfix16_En24
  wire signed [31:0] Multiply5_mul_temp;  // sfix32_En48
  wire signed [15:0] Multiply5_out1;  // sfix16_En15
  reg signed [15:0] delayMatch_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] Multiply5_out1_1;  // sfix16_En15
  wire signed [15:0] Add4_add_cast;  // sfix16_En33
  wire signed [15:0] Add4_add_cast_1;  // sfix16_En33
  wire signed [15:0] Add4_add_temp;  // sfix16_En33
  wire signed [15:0] Add4_out1;  // sfix16_En34
  reg signed [15:0] Delay7_out1;  // sfix16_En34
  wire signed [15:0] Add3_add_cast;  // sfix16_En29
  wire signed [15:0] Add3_add_cast_1;  // sfix16_En29
  wire signed [15:0] Add3_add_temp;  // sfix16_En29
  wire [15:0] Add3_out1;  // ufix16_En30
  reg [15:0] Delay4_out1;  // ufix16_En30
  wire signed [15:0] Add2_add_cast;  // sfix16_En26
  wire signed [15:0] Add2_add_cast_1;  // sfix16_En26
  wire signed [15:0] Add2_add_temp;  // sfix16_En26
  wire signed [15:0] Add2_out1;  // sfix16_En15
  reg signed [15:0] Delay2_out1;  // sfix16_En15
  wire signed [15:0] Add1_add_cast;  // sfix16_En25
  wire signed [15:0] Add1_add_cast_1;  // sfix16_En25
  wire signed [15:0] Add1_add_temp;  // sfix16_En25
  wire [15:0] Add1_out1;  // ufix16_En27
  reg [15:0] Delay3_out1;  // ufix16_En27
  wire [15:0] Add_add_cast;  // ufix16_En25
  wire [15:0] Add_add_cast_1;  // ufix16_En25
  wire [15:0] Add_out1;  // ufix16_En25


  assign HiD_1_out1 = 16'b1111110100111111;


  always @(posedge clk)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        HiD_1_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_1_out1_1 <= HiD_1_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_process
      if (reset == 1'b1) begin
        In_HiD_o_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          In_HiD_o_1 <= In_HiD_o;
        end
      end
    end


  assign Multiply_cast = {1'b0, HiD_1_out1_1};
  assign Multiply_mul_temp = Multiply_cast * In_HiD_o_1;
  assign Multiply_cast_1 = Multiply_mul_temp[31:0];
  assign Multiply_out1 = Multiply_cast_1[30:15];


  always @(posedge clk)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Multiply_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply_out1_1 <= Multiply_out1;
        end
      end
    end



  assign HiD_3_out1 = 16'b1010000101101000;


  always @(posedge clk)
    begin : HwModeRegister2_process
      if (reset == 1'b1) begin
        HiD_3_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_3_out1_1 <= HiD_3_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        Rate_Transition_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition_out1 <= In_HiD_o_1;
        end
      end
    end


  assign Multiply1_cast = {1'b0, HiD_3_out1_1};
  assign Multiply1_mul_temp = Multiply1_cast * Rate_Transition_out1;
  assign Multiply1_cast_1 = Multiply1_mul_temp[31:0];
  assign Multiply1_out1 = Multiply1_cast_1[30:15];


  always @(posedge clk)
    begin : PipelineRegister1_process
      if (reset == 1'b1) begin
        Multiply1_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply1_out1_1 <= Multiply1_out1;
        end
      end
    end



  assign HiD_5_out1 = 16'sb1011110110001111;


  always @(posedge clk)
    begin : HwModeRegister4_process
      if (reset == 1'b1) begin
        HiD_5_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_5_out1_1 <= HiD_5_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_2_process
      if (reset == 1'b1) begin
        Rate_Transition1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition1_out1 <= Rate_Transition_out1;
        end
      end
    end


  assign Multiply2_mul_temp = HiD_5_out1_1 * Rate_Transition1_out1;
  assign Multiply2_out1 = {{10{Multiply2_mul_temp[31]}}, Multiply2_mul_temp[31:26]};


  always @(posedge clk)
    begin : PipelineRegister2_process
      if (reset == 1'b1) begin
        Multiply2_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply2_out1_1 <= Multiply2_out1;
        end
      end
    end



  assign HiD_7_out1 = 16'b1110000101111000;


  always @(posedge clk)
    begin : HwModeRegister6_process
      if (reset == 1'b1) begin
        HiD_7_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_7_out1_1 <= HiD_7_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_3_process
      if (reset == 1'b1) begin
        Rate_Transition2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition2_out1 <= Rate_Transition1_out1;
        end
      end
    end


  assign Multiply3_cast = {1'b0, HiD_7_out1_1};
  assign Multiply3_mul_temp = Multiply3_cast * Rate_Transition2_out1;
  assign Multiply3_cast_1 = Multiply3_mul_temp[31:0];
  assign Multiply3_out1 = Multiply3_cast_1[30:15];


  always @(posedge clk)
    begin : PipelineRegister3_process
      if (reset == 1'b1) begin
        Multiply3_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply3_out1_1 <= Multiply3_out1;
        end
      end
    end



  assign HiD_9_out1 = 16'b1001000100110000;


  always @(posedge clk)
    begin : HwModeRegister8_process
      if (reset == 1'b1) begin
        HiD_9_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_9_out1_1 <= HiD_9_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_4_process
      if (reset == 1'b1) begin
        Rate_Transition3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition3_out1 <= Rate_Transition2_out1;
        end
      end
    end


  assign Multiply4_cast = {1'b0, HiD_9_out1_1};
  assign Multiply4_mul_temp = Multiply4_cast * Rate_Transition3_out1;
  assign Multiply4_cast_1 = Multiply4_mul_temp[31:0];
  assign Multiply4_out1 = Multiply4_cast_1[30:15];


  always @(posedge clk)
    begin : PipelineRegister4_process
      if (reset == 1'b1) begin
        Multiply4_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply4_out1_1 <= Multiply4_out1;
        end
      end
    end



  assign HiD_11_out1 = 16'sb1011100101100110;


  always @(posedge clk)
    begin : HwModeRegister10_process
      if (reset == 1'b1) begin
        HiD_11_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_11_out1_1 <= HiD_11_out1;
        end
      end
    end



  always @(posedge clk)
    begin : HwModeRegister11_process
      if (reset == 1'b1) begin
        Rate_Transition4_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition4_out1 <= Rate_Transition3_out1;
        end
      end
    end



  assign Multiply5_mul_temp = HiD_11_out1_1 * Rate_Transition4_out1;
  assign Multiply5_out1 = {16{Multiply5_mul_temp[31]}};


  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 16'sb0000000000000000;
        delayMatch_reg[1] <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
        end
      end
    end

  assign Multiply5_out1_1 = delayMatch_reg[1];
  assign delayMatch_reg_next[0] = Multiply5_out1;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];



  assign Add4_add_cast = {2'b0, Multiply4_out1_1[15:2]};
  assign Add4_add_cast_1 = 16'sb0000000000000000;
  assign Add4_add_temp = Add4_add_cast + Add4_add_cast_1;
  assign Add4_out1 = {Add4_add_temp[14:0], 1'b0};


  always @(posedge clk)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= Add4_out1;
        end
      end
    end


  assign Add3_add_cast = {1'b0, Multiply3_out1_1[15:1]};
  assign Add3_add_cast_1 = {{5{Delay7_out1[15]}}, Delay7_out1[15:5]};
  assign Add3_add_temp = Add3_add_cast + Add3_add_cast_1;
  assign Add3_out1 = {Add3_add_temp[14:0], 1'b0};


  always @(posedge clk)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= Add3_out1;
        end
      end
    end


  assign Add2_add_cast = {Multiply2_out1_1[4:0], 11'b00000000000};
  assign Add2_add_cast_1 = {4'b0, Delay4_out1[15:4]};
  assign Add2_add_temp = Add2_add_cast + Add2_add_cast_1;
  assign Add2_out1 = {{11{Add2_add_temp[15]}}, Add2_add_temp[15:11]};


  always @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Add2_out1;
        end
      end
    end


  assign Add1_add_cast = {1'b0, Multiply1_out1_1[15:1]};
  assign Add1_add_cast_1 = {Delay2_out1[5:0], 10'b0000000000};
  assign Add1_add_temp = Add1_add_cast + Add1_add_cast_1;
  assign Add1_out1 = {Add1_add_temp[13:0], 2'b00};


  always @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Add1_out1;
        end
      end
    end


  assign Add_add_cast = {1'b0, Multiply_out1_1[15:1]};
  assign Add_add_cast_1 = {2'b0, Delay3_out1[15:2]};
  assign Add_out1 = Add_add_cast + Add_add_cast_1;


  assign Out_HiD_o = Add_out1;

endmodule  // HiD_Odd_block

