// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\db6_2level_final_hdl\HiD_Even.v
// Created: 2024-04-17 20:17:39
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HiD_Even
// Source Path: db6_2level_final_hdl/DWT_db6_2level/1st_Level_Decomp5/HiD_Even
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HiD_Even
          (clk,
           reset,
           enb,
           In_HiD_e,
           Out_HiD_e);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] In_HiD_e;  // ufix16_En24
  output  signed [15:0] Out_HiD_e;  // sfix16_En15


  wire signed [15:0] HiD_0_out1;  // sfix16_En18
  reg signed [15:0] HiD_0_out1_1;  // sfix16_En18
  reg [15:0] In_HiD_e_1;  // ufix16_En24
  wire signed [16:0] Multiply_cast;  // sfix17_En24
  wire signed [32:0] Multiply_mul_temp;  // sfix33_En42
  wire signed [31:0] Multiply_cast_1;  // sfix32_En42
  wire signed [15:0] Multiply_out1;  // sfix16_En15
  reg signed [15:0] Multiply_out1_1;  // sfix16_En15
  wire signed [15:0] HiD_2_out1;  // sfix16_En15
  reg signed [15:0] HiD_2_out1_1;  // sfix16_En15
  reg [15:0] Rate_Transition_out1;  // ufix16_En24
  wire signed [16:0] Multiply1_cast;  // sfix17_En24
  wire signed [32:0] Multiply1_mul_temp;  // sfix33_En39
  wire signed [31:0] Multiply1_cast_1;  // sfix32_En39
  wire signed [15:0] Multiply1_out1;  // sfix16_En15
  reg signed [15:0] Multiply1_out1_1;  // sfix16_En15
  wire [15:0] HiD_4_out1;  // ufix16_En18
  reg [15:0] HiD_4_out1_1;  // ufix16_En18
  reg [15:0] Rate_Transition1_out1;  // ufix16_En24
  wire [31:0] Multiply2_mul_temp;  // ufix32_En42
  wire [15:0] Multiply2_out1;  // ufix16_En26
  reg [15:0] Multiply2_out1_1;  // ufix16_En26
  wire signed [15:0] HiD_6_out1;  // sfix16_En18
  reg signed [15:0] HiD_6_out1_1;  // sfix16_En18
  reg [15:0] Rate_Transition2_out1;  // ufix16_En24
  wire signed [16:0] Multiply3_cast;  // sfix17_En24
  wire signed [32:0] Multiply3_mul_temp;  // sfix33_En42
  wire signed [31:0] Multiply3_cast_1;  // sfix32_En42
  wire signed [15:0] Multiply3_out1;  // sfix16_En15
  reg signed [15:0] Multiply3_out1_1;  // sfix16_En15
  wire [15:0] HiD_8_out1;  // ufix16_En20
  reg [15:0] HiD_8_out1_1;  // ufix16_En20
  reg [15:0] Rate_Transition3_out1;  // ufix16_En24
  wire [31:0] Multiply4_mul_temp;  // ufix32_En44
  wire [15:0] Multiply4_out1;  // ufix16_En29
  reg [15:0] Multiply4_out1_1;  // ufix16_En29
  wire signed [15:0] HiD_10_out1;  // sfix16_En22
  reg signed [15:0] HiD_10_out1_1;  // sfix16_En22
  reg [15:0] Rate_Transition4_out1;  // ufix16_En24
  wire signed [16:0] Multiply5_cast;  // sfix17_En24
  wire signed [32:0] Multiply5_mul_temp;  // sfix33_En46
  wire signed [31:0] Multiply5_cast_1;  // sfix32_En46
  wire signed [15:0] Multiply5_out1;  // sfix16_En15
  reg signed [15:0] delayMatch_reg [0:1];  // sfix16 [2]
  wire signed [15:0] delayMatch_reg_next [0:1];  // sfix16_En15 [2]
  wire signed [15:0] Multiply5_out1_1;  // sfix16_En15
  wire signed [15:0] Add4_add_cast;  // sfix16_En28
  wire signed [15:0] Add4_add_cast_1;  // sfix16_En28
  wire signed [15:0] Add4_add_temp;  // sfix16_En28
  wire [15:0] Add4_out1;  // ufix16_En29
  reg [15:0] Delay7_out1;  // ufix16_En29
  wire signed [15:0] Add3_add_cast;  // sfix16_En26
  wire signed [15:0] Add3_add_cast_1;  // sfix16_En26
  wire signed [15:0] Add3_add_temp;  // sfix16_En26
  wire signed [15:0] Add3_out1;  // sfix16_En15
  reg signed [15:0] Delay4_out1;  // sfix16_En15
  wire signed [15:0] Add2_add_cast;  // sfix16_En25
  wire signed [15:0] Add2_add_cast_1;  // sfix16_En25
  wire signed [15:0] Add2_add_temp;  // sfix16_En25
  wire [15:0] Add2_out1;  // ufix16_En26
  reg [15:0] Delay2_out1;  // ufix16_En26
  wire signed [15:0] Add1_add_cast;  // sfix16_En23
  wire signed [15:0] Add1_add_cast_1;  // sfix16_En23
  wire signed [15:0] Add1_add_temp;  // sfix16_En23
  wire signed [15:0] Add1_out1;  // sfix16_En15
  reg signed [15:0] Delay3_out1;  // sfix16_En15
  wire signed [15:0] Add_out1;  // sfix16_En15


  assign HiD_0_out1 = 16'sb1000110111001000;


  always @(posedge clk)
    begin : HwModeRegister_process
      if (reset == 1'b1) begin
        HiD_0_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_0_out1_1 <= HiD_0_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_process
      if (reset == 1'b1) begin
        In_HiD_e_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          In_HiD_e_1 <= In_HiD_e;
        end
      end
    end


  assign Multiply_cast = {1'b0, In_HiD_e_1};
  assign Multiply_mul_temp = HiD_0_out1_1 * Multiply_cast;
  assign Multiply_cast_1 = Multiply_mul_temp[31:0];
  assign Multiply_out1 = {{11{Multiply_cast_1[31]}}, Multiply_cast_1[31:27]};


  always @(posedge clk)
    begin : PipelineRegister_process
      if (reset == 1'b1) begin
        Multiply_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply_out1_1 <= Multiply_out1;
        end
      end
    end



  assign HiD_2_out1 = 16'sb1001111111011011;


  always @(posedge clk)
    begin : HwModeRegister2_process
      if (reset == 1'b1) begin
        HiD_2_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_2_out1_1 <= HiD_2_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        Rate_Transition_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition_out1 <= In_HiD_e_1;
        end
      end
    end


  assign Multiply1_cast = {1'b0, Rate_Transition_out1};
  assign Multiply1_mul_temp = HiD_2_out1_1 * Multiply1_cast;
  assign Multiply1_cast_1 = Multiply1_mul_temp[31:0];
  assign Multiply1_out1 = {{8{Multiply1_cast_1[31]}}, Multiply1_cast_1[31:24]};


  always @(posedge clk)
    begin : PipelineRegister1_process
      if (reset == 1'b1) begin
        Multiply1_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply1_out1_1 <= Multiply1_out1;
        end
      end
    end



  assign HiD_4_out1 = 16'b1110011110110010;


  always @(posedge clk)
    begin : HwModeRegister4_process
      if (reset == 1'b1) begin
        HiD_4_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_4_out1_1 <= HiD_4_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_2_process
      if (reset == 1'b1) begin
        Rate_Transition1_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition1_out1 <= Rate_Transition_out1;
        end
      end
    end


  assign Multiply2_mul_temp = HiD_4_out1_1 * Rate_Transition1_out1;
  assign Multiply2_out1 = Multiply2_mul_temp[31:16];


  always @(posedge clk)
    begin : PipelineRegister2_process
      if (reset == 1'b1) begin
        Multiply2_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply2_out1_1 <= Multiply2_out1;
        end
      end
    end



  assign HiD_6_out1 = 16'sb1001110000101001;


  always @(posedge clk)
    begin : HwModeRegister6_process
      if (reset == 1'b1) begin
        HiD_6_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_6_out1_1 <= HiD_6_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_3_process
      if (reset == 1'b1) begin
        Rate_Transition2_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition2_out1 <= Rate_Transition1_out1;
        end
      end
    end


  assign Multiply3_cast = {1'b0, Rate_Transition2_out1};
  assign Multiply3_mul_temp = HiD_6_out1_1 * Multiply3_cast;
  assign Multiply3_cast_1 = Multiply3_mul_temp[31:0];
  assign Multiply3_out1 = {{11{Multiply3_cast_1[31]}}, Multiply3_cast_1[31:27]};


  always @(posedge clk)
    begin : PipelineRegister3_process
      if (reset == 1'b1) begin
        Multiply3_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply3_out1_1 <= Multiply3_out1;
        end
      end
    end



  assign HiD_8_out1 = 16'b1000000101011100;


  always @(posedge clk)
    begin : HwModeRegister8_process
      if (reset == 1'b1) begin
        HiD_8_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_8_out1_1 <= HiD_8_out1;
        end
      end
    end



  always @(posedge clk)
    begin : reduced_4_process
      if (reset == 1'b1) begin
        Rate_Transition3_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition3_out1 <= Rate_Transition2_out1;
        end
      end
    end


  assign Multiply4_mul_temp = HiD_8_out1_1 * Rate_Transition3_out1;
  assign Multiply4_out1 = Multiply4_mul_temp[30:15];


  always @(posedge clk)
    begin : PipelineRegister4_process
      if (reset == 1'b1) begin
        Multiply4_out1_1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Multiply4_out1_1 <= Multiply4_out1;
        end
      end
    end



  assign HiD_10_out1 = 16'sb1011000110111011;


  always @(posedge clk)
    begin : HwModeRegister10_process
      if (reset == 1'b1) begin
        HiD_10_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          HiD_10_out1_1 <= HiD_10_out1;
        end
      end
    end



  always @(posedge clk)
    begin : HwModeRegister11_process
      if (reset == 1'b1) begin
        Rate_Transition4_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Rate_Transition4_out1 <= Rate_Transition3_out1;
        end
      end
    end



  assign Multiply5_cast = {1'b0, Rate_Transition4_out1};
  assign Multiply5_mul_temp = HiD_10_out1_1 * Multiply5_cast;
  assign Multiply5_cast_1 = Multiply5_mul_temp[31:0];
  assign Multiply5_out1 = {{15{Multiply5_cast_1[31]}}, Multiply5_cast_1[31]};


  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg[0] <= 16'sb0000000000000000;
        delayMatch_reg[1] <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= delayMatch_reg_next[0];
          delayMatch_reg[1] <= delayMatch_reg_next[1];
        end
      end
    end

  assign Multiply5_out1_1 = delayMatch_reg[1];
  assign delayMatch_reg_next[0] = Multiply5_out1;
  assign delayMatch_reg_next[1] = delayMatch_reg[0];



  assign Add4_add_cast = {1'b0, Multiply4_out1_1[15:1]};
  assign Add4_add_cast_1 = {Multiply5_out1_1[2:0], 13'b0000000000000};
  assign Add4_add_temp = Add4_add_cast + Add4_add_cast_1;
  assign Add4_out1 = {Add4_add_temp[14:0], 1'b0};


  always @(posedge clk)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= Add4_out1;
        end
      end
    end


  assign Add3_add_cast = {Multiply3_out1_1[4:0], 11'b00000000000};
  assign Add3_add_cast_1 = {3'b0, Delay7_out1[15:3]};
  assign Add3_add_temp = Add3_add_cast + Add3_add_cast_1;
  assign Add3_out1 = {{11{Add3_add_temp[15]}}, Add3_add_temp[15:11]};


  always @(posedge clk)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= Add3_out1;
        end
      end
    end


  assign Add2_add_cast = {1'b0, Multiply2_out1_1[15:1]};
  assign Add2_add_cast_1 = {Delay4_out1[5:0], 10'b0000000000};
  assign Add2_add_temp = Add2_add_cast + Add2_add_cast_1;
  assign Add2_out1 = {Add2_add_temp[14:0], 1'b0};


  always @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Add2_out1;
        end
      end
    end


  assign Add1_add_cast = {Multiply1_out1_1[7:0], 8'b00000000};
  assign Add1_add_cast_1 = {3'b0, Delay2_out1[15:3]};
  assign Add1_add_temp = Add1_add_cast + Add1_add_cast_1;
  assign Add1_out1 = {{8{Add1_add_temp[15]}}, Add1_add_temp[15:8]};


  always @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= Add1_out1;
        end
      end
    end


  assign Add_out1 = Multiply_out1_1 + Delay3_out1;


  assign Out_HiD_e = Add_out1;

endmodule  // HiD_Even

